### ISSUE TITLE
Making FragmentState an Object in RenderPipelineDescriptor instead of a ptr.

### ISSUE THREAD

**Issue by lokokung** [webgpu-native/webgpu-headers#112]
Right now in RenderPipelineDescriptor, VertexState is an object, not a pointer since it is easier to just modify it (with it already allocated). IIUC, FragmentState is a pointer right now only because it is optional. It would be nice if FragmentState was also an already allocated object in the descriptor, and we could use an internal member's null-ness to determine if we have any FragmentState. (i.e. we could check if FragmentState.module is null to determine if we have an actual FragmentState). 

This way, Vertex and Fragment state can be consistent with one another.

**Comment by aloucks** [comment]
Although I'm always a fan of keeping things consistent, I don't think having logic around an inner field accomplishes that goal. Checking an inner field feels more like a hack than a real solution.

I think a better option would be to use tagged unions to allow for optional fields. The challenge is that in order to be consistent, every optional item in the API should leverage a tagged union. That's a much larger change and introduces a small amount of complexity over just using a null pointer.

**Comment by Kangz** [comment]
This was discussed in https://github.com/webgpu-native/webgpu-headers/pull/81. There's tension between making the C header nicer to use (including when naively translated to C++) and making it reflect exactly the JS API with different language bindings making the descriptor nicer (for example using `Option<FragmentState>` in Rust). We could revisit, but IMHO for Dawn we could assume that someone, someday, will make a nicer C++ binding for this header.

**Comment by kainino0x** [comment]
webgpu.h meeting: This ended up tying into two other issues. #242: If we make WGPUFragmentState.module optional (nullable) to represent this, then what will we do if the JS API makes it optional in the future? (There was discussion of whether this was needed for z-prepass - need to figure out how you're supposed to do z-prepass in WebGPU JS in the same render pass with the main rendering). If we want to use a different sentinel value than `nullptr` then we run into the same problem as #166 (which we do also have to solve).

**Comment by kainino0x** [comment]
webgpu.h meeting (oct 26): we should leave this as is, we didn't have a better suggestion. If we need to make it optional in the future we can have some extra boolean field.

**Comment by kainino0x** [comment]
options considered were:
- sentinel unaligned pointer value (this is probably not legal C)
- use shaderModule=null as the sentinel - we think it's reasonably possible that we'll end up needing to use this to express a pipeline with attachments but no fragment shader
