### ISSUE TITLE
API contract for wgpuInstanceProcessEvents() is unclear

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#117]
Its not clear whether it supposed to block or not, and how it integrates with an already-existing runloop.

**Comment by litherum** [comment]
I suppose it has to be reentrant, then, huh.

**Comment by Kangz** [comment]
Reentrant? But yeah during the processing you have to support more callbacks being added to the queue (and first move the queue, then process it, to avoid iterator invalidation)

**Comment by kainino0x** [comment]
I don't think wgpuInstanceProcessEvents() needs to be callable from within a callback running inside wgpuInstanceProcessEvents(). But yes to the stuff Corentin said.
