### ISSUE TITLE
nullable annotations would be useful

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#119]
It would help implementations know what's allowed to be null and what isn't.

https://clang.llvm.org/docs/analyzer/developer-docs/nullability.html

**Comment by litherum** [comment]
Bump. It's unclear if a create method fails due to a validation failure, if it should return `nullptr` or an invalid object.

**Comment by Kangz** [comment]
See #157 for arguments to the API.

In general return values that are object are never null, and instead are invalid objects, like the JS API.

**Comment by litherum** [comment]
I was thinking of __nullable from https://clang.llvm.org/docs/analyzer/developer-docs/nullability.html ...

**Comment by Kangz** [comment]
Erhm, that's non-standard and just an LLVM thing. That header also needs to be compatible with other C compilers like GCC or MSVC. At best we could do a `WGPU_NULLABLE` define that default to being an empty list of tokens but can be overriden.

**Comment by litherum** [comment]
`WGPU_NULLABLE` sounds like the perfect solution.

**Comment by kainino0x** [comment]
Partially addressed in #182, but there were some open follow-up questions:
https://github.com/webgpu-native/webgpu-headers/pull/182#pullrequestreview-1437806420

**Comment by kainino0x** [comment]
Added the important item from there to #190. Closing this issue, so we can track there.
