### ISSUE TITLE
WGPUShaderModuleDescriptor has nothing in it

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#120]
It probably at least needs [`const char* code`](https://gpuweb.github.io/gpuweb/#dom-gpushadermoduledescriptor-code).

**Comment by austinEng** [comment]
That's in `WGPUShaderModuleWGSLDescriptor` though it should be renamed from `source` to `code` to match WebGPU.

**Comment by litherum** [comment]
Got it.
