### ISSUE TITLE
WGPUVertexState's buffers array can't be sparse

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#121]
WebGPU [has](https://gpuweb.github.io/gpuweb/#dom-gpuvertexstate-buffers)

```
sequence<GPUVertexBufferLayout?> buffers = [];
```

So each item inside the array can be null.

However, these headers have:
```
typedef struct WGPUVertexBufferLayout {
    uint64_t arrayStride;
    WGPUVertexStepMode stepMode;
    uint32_t attributeCount;
    WGPUVertexAttribute const * attributes;
} WGPUVertexBufferLayout;
...
WGPUVertexBufferLayout const * buffers;
```

This array appears to have to be dense.

**Comment by Kangz** [comment]
The intent of the header is that this array has to be dense, but that skipped JS elements can just have 0 attributes. In terms of validation for the WebGPU API it should be exactly the same because render pipelines only validate against attributes, and draw-time validation walks all the attributes, not the buffers.

**Comment by litherum** [comment]
🆗

**Comment by litherum** [comment]
Similar question: WebGPU [has](https://gpuweb.github.io/gpuweb/#dictdef-gpurenderpassdescriptor)

```
required sequence<GPURenderPassColorAttachment?> colorAttachments;
```

So each item inside the array can be null.

However, these headers have:

```
typedef struct WGPURenderPassColorAttachment {
    WGPUTextureView view;
    WGPUTextureView resolveTarget;
    WGPULoadOp loadOp;
    WGPUStoreOp storeOp;
    WGPUColor clearColor;
} WGPURenderPassColorAttachment;
...
WGPURenderPassColorAttachment const * colorAttachments;
```

Presumably the value supplied to `@location()` in WGSL corresponds to an index into this array, so I don't think we can just pack the color attachments together like we can for the WGPUVertexState.

Maybe if both `view` and `resolveTarget` are null, that means "this item represents a hole"?

The same problem occurs with `GPUFragmentState` and `GPURenderPassLayout`.

**Comment by Kangz** [comment]
I think that `view == NULL` means it is a whole. Same thing with `format == WGPUTextureFormat_Undefined` for the other structures. (IIRC that's what Dawn currently does, but as usual it could be changed)

**Comment by litherum** [comment]
Just `view == NULL`? How does one say "render using multisampling and resolve that multisampling without an intermediate texture"? (This is pretty important on TBDR)

**Comment by Kangz** [comment]
I don't think that's currently possible in WebGPU (D3D12 doesn't allows it?), but agreed it would be an important capability for an optional feature or other. It would have both `view == nullptr` and `resolveTarget == nullptr` like you said.
