### ISSUE TITLE
WGPUPowerPreference does not have a "no preference" option

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#125]
The `powerPreference` field in [`GPURequestAdapterOptions`](https://gpuweb.github.io/gpuweb/#dictdef-gpurequestadapteroptions) is optional, and there's no way to represent its absence in these headers.

**Comment by Kangz** [comment]
I'll make a PR for that. In general I think we should have all enums have "undefined" so they can represent JS undefined. This is already the case for a bunch of them.
