### ISSUE TITLE
Formulation of features doesn't match WebGPU API

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#129]
In WebGPU, they're exposed as:

```
interface GPUSupportedFeatures {
    readonly setlike<DOMString>;
};
...
readonly attribute GPUSupportedFeatures features;
```

This `setlike` interface doesn't match these headers, which just have

```
WGPU_EXPORT bool wgpuAdapterHasFeature(WGPUAdapter adapter, WGPUFeatureName feature);
```

**Comment by Kangz** [comment]
How would you expose a set-like via a C API? In this case it is a set with a fixed list of known values for browsers so a browser can iterate through all of them and ask `HasFeature` for each individual one.

**Comment by kainino0x** [comment]
setlikes are also iterable. We could just expose it as an array and it would be pretty close.

**Comment by litherum** [comment]
Is this done? I think this is done.
