### ISSUE TITLE
Unclear what signalValue means

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#130]
It's only used in one place. What value should callers pass in? What should implementations do with it?

**Comment by Kangz** [comment]
They should validate that it is 0 :)

The idea is that it is harder for webgpu.h APIs to be extended with extra arguments so we sometimes try to predict what extra arguments will be needed. In this case is it the signal value from some multi-queue proposals. More specifically https://github.com/gpuweb/gpuweb/issues/1073

But maybe it should be removed and instead we can have a `wgpu::Queue::OnSignalPassed(signalValue)`. WDYT?

@kvark WDYT too?

**Comment by kvark** [comment]
Sure, fine to remove this
