### ISSUE TITLE
Support Wayland

### ISSUE THREAD

**Issue by rajveermalviya** [webgpu-native/webgpu-headers#139]
Currently only X11 is supported by `WGPUSurfaceDescriptorFromXlib`.
Any planning on supporting Wayland?

**Comment by Kangz** [comment]
That would be easy to add similarly to [VkWaylandSurfaceCreateInfoKHR](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkWaylandSurfaceCreateInfoKHR.html)
