### ISSUE TITLE
GPUShaderModuleDescriptor.hints is not modeled

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#147]
There is no `hints` field in GPUShaderModuleDescriptor. It is present in https://gpuweb.github.io/gpuweb/#dictdef-gpushadermoduledescriptor. There's also no `GPUShaderModuleCompilationHint`.

**Comment by Kangz** [comment]
What do you think of the following prototype diff:

```diff
 struct GPUShaderModuleDescriptor {
     // Existing stuff
+    uint32_t hintCount;
+    WGPUCompilationHints * const hints;
 }

+struct GPUShaderModuleCompilationHint {
+     WGPUChainedStruct const * nextInChain;
+     char * const entryPoint;
+     WGPUPipelineLayout layout;
+     // Do we need to add more stuff here for v1?
+}
```

Alternatively the addition of `hints` could be done via a chained struct.

**Comment by litherum** [comment]
> What do you think

I'm not allowed to have opinions.

That being said, your suggestion is very similar to what I've been working with in WebKit: https://trac.webkit.org/browser/webkit/trunk/Source/WebGPU/WebGPU/WebGPUExt.h#L64

**Comment by kainino0x** [comment]
prototype diff LGTM, it's in the core API so I think it's fine to put in GPUShaderModuleDescripter directly
