### ISSUE TITLE
Flag enum types and flags typedefs

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#159]
_Originally posted by @mrshannon in https://github.com/webgpu-native/webgpu-headers/issues/158#issuecomment-1146170716_:

> > Any idea on how to improve WGPUBufferUsage vs. WGPUBufferUsageFlags?
> 
> You technically don't need `WGPUBufferUsageFlags` as `WGPUBufferUsage` will > always be wide enough for the bitwise combination because we have `WGPUBufferUsage_Force32 = 0x7FFFFFFF` which is effectively doing what is done for the C++ headers with:
> ```c++
> enum class BufferUsage : uint32_t {
> ```

This is strictly true, but in Dawn's C++ bindings we also have operator overloads, so when you do `wgpu::BufferUsage::CopySrc | wgpu::BufferUsage::CopyDst` you get a `wgpu::BufferUsage` value. In C `WGPUBufferUsage_CopySrc | WGPUBufferUsage_CopyDst` will give you an int of some kind. So this would force callers of the API to cast back to the appropriate type.

```c
desc.usage = static_cast<WGPUBufferUsage>(WGPUBufferUsage_CopySrc | WGPUBufferUsage_CopyDst);
```

Apparently, the cast is only needed in C++. C seems happy without a cast. So I guess we could define operator overloads for these types behind `#ifdef __cplusplus`...?

**Comment by kainino0x** [comment]
i.e.

```c
#ifdef __cplusplus
WGPUBufferUsage operator|(WGPUBufferUsage a, WGPUBufferUsage b) {
    return static_cast<WGPUBufferUsage>(a | b);
}
```

and so on

**Comment by kainino0x** [comment]
FWIW, we copied this pattern from Vulkan:
https://github.com/webgpu-native/webgpu-headers/pull/1#discussion_r303507976

in any case, whatever we do, we need to make sure it works fully in both C and C++.

**Comment by Kangz** [comment]
Adding operators only in C++ if that's where it causes problems would make sense. We could have something similar to Dawn's [`EnumClassBitmask.h`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/include/dawn/EnumClassBitmasks.h;l=16?q=EnumClassBit&sq=).

> in any case, whatever we do, we need to make sure it works fully in both C and C++.

Yeah right now webgpu.h doesn't work in C because of #84 even.

**Comment by kainino0x** [comment]
A Dawn contributor just so happened to [find](https://dawn-review.googlesource.com/c/dawn/+/87381) a pattern just like this in mingw's `winnt.h`: https://github.com/mirror/mingw-w64/blob/1de9cc347da5215889f6e8ff3bd4bcc820aa50bf/mingw-w64-headers/include/winnt.h#L682

```cpp
#ifdef __cplusplus
#define DEFINE_ENUM_FLAG_OPERATORS(ENUMTYPE) \
extern "C++" { \
inline ENUMTYPE operator | (ENUMTYPE a, ENUMTYPE b) { return ENUMTYPE(((int)a) | ((int)b)); } \
...
```

**Comment by kainino0x** [comment]
meeting: agreed to do that, to patch over the difference between C and C++.

However I forgot that the original point of this issue was whether we wanted to _get rid of_ the \*Flags types, as we don't need this change otherwise (in C++, `enum | enum` -> `int`). I think we should get rid of the Flags types.

**Comment by kainino0x** [comment]
Obsoleted by #273 due to replacing all bitflag enums with uint64_t.
