### ISSUE TITLE
Add support for null targets in WGPUFragmentState

### ISSUE THREAD

**Issue by mrshannon** [webgpu-native/webgpu-headers#160]
The JavaScript API allows individual targets to be `null`
```
dictionary GPUFragmentState : GPUProgrammableStage {
    required sequence<GPUColorTargetState?> targets;
};
```
which allows holes in the array of color attachments.

With `webgpu.h` we can pass `NULL` for the entire fragment state, or pass a 0 length `targets` array but cannot skip color attachments.

**Comment by Kangz** [comment]
The intent as @kainino0x described on the matrix channel is that setting `WGPUColorTarget::format` to `WGPUTextureFormat_Undefined` means a hole. There's a bunch of additional semantics that aren't described in the header like this that we should document in this repo. Keeping the issue open until that documentation is done if that's ok with you.

**Comment by kainino0x** [comment]
meeting: Agreed to stick with that. Adding the "needs docs" tag and closing as no API change is needed.

**Comment by kainino0x** [comment]
Docs done in #364
