### ISSUE TITLE
Misleading and confusing name: nextInChain

### ISSUE THREAD

**Issue by jupahe64** [webgpu-native/webgpu-headers#171]
While making c# Wrapper types for wgpu I stumbled upon nextInChain a LOT, there is no explanation what it is and took quite some time to match them with other APIs to figure out what they actually represent in the context of the given GPU object

I understand why WGPUChainedStruct is a thing, sort of, but I really don’t understand why it should influence the naming of variables which are crucial to understanding and using the API

My proposal is to either give them appropriate names or atleast add comments describing what they are actually used for (in context)

I realize that this is supposed to be THE interface that everyone is supposed to be implementing, so it’s probably to late for the first option but I think comments would still be appreciated.

also if someone could point me to the discussion that led up to this naming and the concept of WGPUChainedStruct it would really be appreciated aswell, because it makes working with the API unnecessarily complicated.

**Comment by Kangz** [comment]
`nextInChain` is similar to the Vulkan [`pNext`](https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#fundamentals-validusage-pNext): it is a way to extend structures with additional members and is used for extensions and some part of the core WebGPU structures. Given this, it doesn't seem like `nextInChain` influences the naming of other members, it is just the name of the start of the extension chain. The extension structures have a comment describing which chain they can be part of, for example [here](https://github.com/webgpu-native/webgpu-headers/blob/fa1c6ab4927ef1fa5731907b42b62ea93119866c/webgpu.h#L924).

In the vast majority of cases developers don't need to set the `nextInChain` and it can be left 0-initialized, though yeah it's annoying when writing bindings. The discussions around `nextInChain` happened mostly offline and were based on the precedent of Vulkan's `pNext` so unfortunately the best trace is the Vulkan spec link above or https://github.com/webgpu-native/webgpu-headers/pull/30.

**Comment by jupahe64** [comment]
I see, this definitely gave me a much better understanding of the underlying principle.
I might have to rethink my wrappers then.

Thanks a lot for the fast and thorough response!
