### ISSUE TITLE
Why does wgpuBufferGetUsage return WGPUBufferUsage instead of WGPUBufferUsageFlags?

### ISSUE THREAD

**Issue by mwyrzykowski** [webgpu-native/webgpu-headers#172]
The declaration for wgpuBufferGetUsage is:

`WGPUBufferUsage wgpuBufferGetUsage(WGPUBuffer buffer)`

but a WGPUBuffer may have multiple usages. Shouldn't it return `WGPUBufferUsageFlags` instead?

**Comment by mwyrzykowski** [comment]
The same issue exists for `WGPUTextureUsage wgpuTextureGetUsage(WGPUTexture texture)`

**Comment by Kangz** [comment]
Good catch, we should fix this.
