### ISSUE TITLE
Pass DeviceLostCallback in at device creation time. 

### ISSUE THREAD

**Issue by toji** [webgpu-native/webgpu-headers#173]
The WebGPU spec was changed a little while back to [return a device which has already been lost](https://gpuweb.github.io/gpuweb/#dom-gpuadapter-requestdevice) rather than a null device if requestDevice fails. This poses some complications for the current `wgpuDeviceSetDeviceLostCallback()` API in webgpu.h

Since `wgpuDeviceSetDeviceLostCallback()` cannot be called until a device is acquired, with the updated logic there's no way to set the callback until the device has already been lost. This then necessitates that the lost reason and message be cached if there is not callback set until a callback is eventually set, which would fire immediately upon setting. When attempting to implement this in Dawn I found that the logic was unexpectedly tricky and contained multiple subtle edge cases.

A cleaner alternative would be to pass the device lost callback and userdata in at device creation time as part of the descriptor and remove the `wgpuDeviceSetDeviceLostCallback()` call entirely. This way the device will be able to use a unified path for handling any device loss at any point in time. Applications that need more flexibility will still be able to build their own message propagation system on top of it, and can probably do it more confidently since this change would remove questions such as "What happens if I set the callback twice?"

New descriptor would look like this:

```diff
typedef struct WGPUDeviceDescriptor {
    WGPUChainedStruct const * nextInChain;
    char const * label; // nullable
    uint32_t requiredFeaturesCount;
    WGPUFeatureName const * requiredFeatures;
    WGPURequiredLimits const * requiredLimits; // nullable
    WGPUQueueDescriptor defaultQueue;
+   WGPUDeviceLostCallback deviceLostCallback;
+   void * deviceLostUserdata;
} WGPUDeviceDescriptor;
```

Any concerns?

**Comment by Kangz** [comment]
I would like the opinion from wgpu folks as well: @cwfitzgerald @teoxoy?

**Comment by teoxoy** [comment]
The proposal looks solid to me.

**Comment by Beyley** [comment]
This seems to have been completed in
https://github.com/webgpu-native/webgpu-headers/commit/8f819a4902c8d644aa6fa11ab9945150a67c69cc

**Comment by kainino0x** [comment]
Indeed!
