### ISSUE TITLE
Figure out when callbacks are called, and on what thread

### ISSUE THREAD

**Issue by austinEng** [webgpu-native/webgpu-headers#18]
Currently in Dawn, we have to call device.Tick() repetitively in order to make progress and receive callbacks. If there are any pending callbacks, they're resolved on the same thread that you call Tick(). We've been thinking about removing Tick and checking callback completion on a separate thread. This has opened up a couple of possible ways forward, and we should have the behavior consistent for users of webgpu.h

### 1. Use Tick
- Calling this in a loop is particularly wasteful.
- It's easy to misuse -- calling it often all the time or not at all
- It isn't part of the JavaScript API.
- It does however  let the application most explicitly control when callbacks are delivered
- May require an application to do their own cross-thread posting if they want to process the callback somewhere else

### 2. Call callbacks on a separate thread
- May require an application to do their own cross-thread posting if they want to process the callback somewhere else
- The application receives the callback on a thread it didn't create -- exposing an implementation detail

### 3. Forward callbacks to the originating thread
- May require an application to do their own cross-thread posting if they want to process the callback somewhere else
- Requires the implementation to check at every / most API calls if there's a callback to process
- This is **probably** where an application wants to receive a callback, so it's nice if we do it for them.

---

I lean toward option (2). Having (1) is a fairly inefficient solution. I don't want to have the implementation do extra work to implement (3), especially if an application already manages cross-thread tasks itself.

**Comment by kainino0x** [comment]
I think it would make sense to be closer to the pattern of other libraries like SDL (though maybe not exactly SDL).

The idea is we should slim down and rename Tick such that apps can call it in a reasonable way. This may require two entry points

one which allows
```c
while (true) {
  wgpuProcessEvents();
  render();
  swapBuffers(); // rate limited here
}
```

and one which allows

```c
function myCallbackThreadMain() {
  while (true) {
    wgpuWaitForAndProcessEvents(); // always waits for at least one event before returning
  }
}
```

**Comment by Kangz** [comment]
+1, and because it is essentially a global object, maybe it could be on the `WGPUDevice` object ^^.

**Comment by kvark** [comment]
Relevant - https://github.com/gfx-rs/wgpu/pull/377

**Comment by austinEng** [comment]
I like the idea of having an event loop, although thinking about this again recently, I realized it may need to be a *per-thread* event loop?

If there's only a single event loop, then native apps will expect to be handling events on whatever thread they call `WGPUEventLoop.tick` or `WGPUEventLoop.run_forever`. With WASM, this won't be the case because the Javascript event loop will resolve promises on the originating thread.

**Comment by Kangz** [comment]
Thanks @kvark for the pointer. It's interesting that the event loop is a separate objects passed to callbacks. Before device creation I'm not sure how important the event loop is, it seems hard to make engine initialization async, and forcing to process the event loop in a synchronous manner doesn't help, you need to yield to the browser in WASM.

**Comment by grovesNL** [comment]
@Kangz 
> It's interesting that the event loop is a separate objects passed to callbacks.

Open to other ideas :) In the sketch we basically just provide the event loop whenever a callback is provided. I think providing it would allow per-thread event loops like @austinEng mentioned.

Another idea is to bind the event loop to the adapter/device as you mentioned above (so we only pass the event loop once), or we create the event loop internally and expose it somehow. 

> Before device creation I'm not sure how important the event loop is

It's only important because `request_adapter` is asynchronous. Ideally we could share as much of the WebGPU API between native and web as possible, so I think we should try to avoid making `request_adapter` synchronous on native but asynchronous on web.

> forcing to process the event loop in a synchronous manner doesn't help, you need to yield to the browser in WASM

We can still yield through callbacks (without spinning) as usual. For example, engines will already need to do this for buffer mapping callbacks too.

**Comment by Kangz** [comment]
We had a good chat about this with @kvark (thanks!) here's a brief summary.

There are several usecases that would need to be addressed:
 
 - In `wgpu-rs` (the nice Rust wrapper to webgpu.h) it would be great to integrate with the `winit` crate (GLFW like, but with its own event loop) such that callbacks are called outside of the frame function.
 - In C++ it would be good to give applications control over when callbacks are fired so they can do it at the start of their frame function.
 - In emscripten we should fire the callbacks outside of the frame function called by emscripten.

There was also the question of how WebGPU does frame pacing, we haven't resolved it but we agreed WebGPU shouldn't take control of the frame pacing for you (that's winit's job). This naturally leads to having a `ProcessEvents` method on some object that's the only time callbacks can be fired. TBD if each thread needs to fire its own callback or if they are all fired in the `ProcessEvent` call of whichever thread does the call.

In wgpu-rs the `ProcessEvent` is hidden inside winit which would map nicely to yielding to the browser and getting the events fired. In C++ + emscripten it's a bit more ugly, but maybe we could make `ProcessEvent` do nothing and produce a warning, telling people to yield to the browser instead. (and when we have `requestMainLoop` that might change ^^)

And we agree that an instance object is useful and `ProcessEvent` could be on that object.

**Comment by kainino0x** [comment]
I was actually thinking we could make the ProcessEvent API work as expected on Emscripten. We just have to queue up the callbacks and call them only in ProcessEvent.

**Comment by kvark** [comment]
After a bit more thought and discussions, we are leaning towards the `Future`-based API for all asynchronous stuff, see https://github.com/gfx-rs/wgpu-rs/pull/120 . This means `winit` event loop is not necessarily involved.

> There was also the question of how WebGPU does frame pacing, we haven't resolved it but we agreed WebGPU shouldn't take control of the frame pacing for you (that's winit's job).

I think there is a miscommunication here. Winit can't drive the frame pacing if the user is able to get frames and submit them independently of the events.

**Comment by Kangz** [comment]
> After a bit more thought and discussions, we are leaning towards the Future-based API for all asynchronous stuff, see gfx-rs/wgpu-rs#120 . This means winit event loop is not necessarily involved.

For Rust a `Future` based API would seem (at least to an outsider like me) the most direct translation of the JS futures. You were concerned that the current webgpu.h didn't allow for frame pacing, maybe we could say the applications should watch frames go by with fences on their own, WDYT?

> I think there is a miscommunication here. Winit can't drive the frame pacing if the user is able to get frames and submit them independently of the events.

Makes sense.

**Comment by litherum** [comment]
The last comment on this is almost 2 years old. A resolution here would be helpful.

**Comment by kvark** [comment]
The current state of things, where applications use their own event loops and just call Tick(), is acceptable to us at this stage. Therefore, no progress was made on the issue. Adding a hidden thread doesn't excite me personally, since we'd not be able to do the polling optimally on it, anyway. The polling could interrupt an important piece of user work (like VR reprojection) at the wrong time, or could delay the resolution of a Map() call longer than they need. Since we can't make it best, it's reasonable to let users control polling.

**Comment by Kangz** [comment]
And maybe we can have platform-specific extension to block on GPU events if that's needed.

**Comment by litherum** [comment]
What is Tick()?

**Comment by Kangz** [comment]
The thing that ticks the "GPU event loop". In Dawn that's currently `wgpu::Device::Tick` because we don't implement `ProcessEvents`.

**Comment by kainino0x** [comment]
Forgot we had this issue. #199 will answer this, so calling this superseded.
