### ISSUE TITLE
GetMappedRange pointer relative addresses and alignment guarantees

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#180]
This is an API contract question. When you GetMappedRange twice from the same MapAsync, must they be suballocated out of one address space (malloc in MapAsync) such that you can do pointer arithmetic to get between the two? Or can they be unrelated allocations (malloc in GetMappedRange)?

Pointer arithmetic doesn't seem very necessary, and the latter can obviously be lighter on memory (mainly in WASM), but it's worth saying this explicitly because in most native implementations they will just be pointers into one memory region.

- [x] Relative pointer addresses: **No**
- [x] Pointer alignment: **16 bytes**

See also #66, #57.

**Comment by kainino0x** [comment]
Another question has come up here, what is the guaranteed alignment of these pointers?
https://github.com/emscripten-core/emscripten/pull/19477

256 bytes seems acceptable to me.

**Comment by grovesNL** [comment]
We had the same alignment question about alignment guarantees for mapped buffers in wgpu https://github.com/gfx-rs/wgpu/issues/3508

**Comment by kainino0x** [comment]
> I'll also note that getMappedRange won't guarantee the alignment on its own. For example if you getMappedRange with an offset of 8, you shouldn't expect something that's 16-byte aligned. Most likely what's guaranteed to be aligned is (the pointer you get, minus your getMappedRange offset, minus your mapAsync offset) or something along those lines.

**Comment by kainino0x** [comment]
> * [ ]  Relative pointer addresses

webgpu.h meeting today: we're fine with not guaranteeing relative addresses of the pointers from two different GetMappedRange calls. Unlikely to be a problem. Can always guarantee this later if it somehow becomes necessary.

> * [ ] Pointer alignment

To discuss more

**Comment by kainino0x** [comment]
Vulkan: requires an alignment of 64: https://registry.khronos.org/vulkan/specs/1.0/html/chap32.html#limits-minmax
And indeed that alignment is for "map pointer minus offset":
> minMemoryMapAlignment is the minimum required alignment, in bytes, of host visible memory allocations within the host address space. When mapping a memory allocation with [vkMapMemory](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkMapMemory.html), subtracting offset bytes from the returned pointer will always produce an integer multiple of this limit.

D3D12: D3D11, at least, requires an alignment of 16: https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#5.6.1%20Mapping

Metal: I don't know how to look this up, but MoltenVK seems to know the alignment (16, 64, or 256) and now clamps up to 64 if the device doesn't support the alignment. I don't know how they make this work though.
https://github.com/search?q=repo%3AKhronosGroup/MoltenVK%20mtlBufferAlignment&type=code

**Comment by kainino0x** [comment]
Meeting:
Guarantee 16. In the future, if we can find a way to paper over backends, we'd like to guarantee 64.

**Comment by kainino0x** [comment]
I tried to implement this and found out that OpenGL ES does not guarantee alignment. Dawn fails an alignment assertion when using its OpenGL ES backend on ANGLE-on-DX11 on Win10/NVIDIA.

In desktop GL 4.2+ "the returned pointer will reflect an allocation aligned to the value of GL_MIN_MAP_BUFFER_ALIGNMENT basic machine units" and the minimum value of that is 64 (nice!)

We may need to expose different limits per adapter. I don't suspect there's a great way to paper over smaller alignments in backends because drivers _can_ totally just implement mapping as a malloc() which can have a different alignment every time.

Unfortunately I couldn't find an explanation of how MoltenVk can provide this limit when Metal doesn't provide it. The PR was https://github.com/KhronosGroup/MoltenVK/pull/1357. [VK_KHR_portability_subset](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_subset.html) also doesn't seem to allow exposing lower limits.

**Comment by kainino0x** [comment]
For the record here's the Dawn change where I saw failures:
https://dawn-review.googlesource.com/c/dawn/+/162103/5
And I finally got them to repro on a tryjob (32-bit windows, ANGLE on D3D11)
https://ci.chromium.org/ui/p/chromium/builders/try/dawn-try-win10-x86-rel/1465/test-results?sortby=&groupby=

Meeting:

*   AE: Problem for auto-vectorization or manual simd?
*   CF: We run into this all the time because a common math library uses simd for vec4
*   KN: Auto-vectorization wouldn’t run because it can’t tell what the alignment of void\* is. Maybe we should try to fix this by returning a pointer type that has a known alignment?
*   CF: People run into issues even casting up to float (4-byte). Surprised if GLES actually doesn’t align in practice.
*   KN: Would be very surprised if alignment isn’t at least 8 for u64/f64.
*   …
*   KN: The actual configuration that I saw this fail on was ANGLE. It may be that we can just make ANGLE give a better alignment and other drivers already provide this in practice. We’ll still have the assertion in Dawn so if people run up against drivers that don’t, hopefully they will report it to us
*   AE: ANGLE is using malloc for 3 types of map, so it’s likely just that.
*   **KN to investigate increasing the alignment in ANGLE**

**Comment by austinEng** [comment]
here's what I found in ANGLE. the relevant class is [Buffer11](https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/renderer/d3d/d3d11/Buffer11.h;drc=8e78783dc1f7007bad46d657c9f332614e240fd8;bpv=1;bpt=1;l=52)::[BufferStorage](https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/renderer/d3d/d3d11/Buffer11.cpp;drc=8e78783dc1f7007bad46d657c9f332614e240fd8;bpv=1;bpt=1;l=108?gsn=BufferStorage&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fchromium.googlesource.com%2Fcodesearch%2Fchromium%2Fsrc%2F%2Fmain%3Flang%3Dc%252B%252B%3Fpath%3Dthird_party%2Fangle%2Fsrc%2FlibANGLE%2Frenderer%2Fd3d%2Fd3d11%2FBuffer11.cpp%23BufferStorage%253Arx%2523c%2523bTSPg8aJjij)

which has 4 backings:
 - NativeStorage
 - EmulatedIndexStorage
 - PackStorage
 - SystemMemoryStorage

NativeStorage calls  D3D's map directly.

The other 3 of those essentially do `return mMemoryBuffer.data() + offset`;
This is [angle::MemoryBuffer](https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/common/MemoryBuffer.h;l=20;drc=8e78783dc1f7007bad46d657c9f332614e240fd8;bpv=1;bpt=1) which allocates by doing `malloc`.

**Comment by kainino0x** [comment]
I never did manage to increase the alignment in ANGLE, but Austin's investigation showed it should be no problem so I'm going to close this and just leave it as "needs docs".
