### ISSUE TITLE
WGPUBufferMapAsyncStatus error codes

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#183]
Right now we have a bunch of error codes in WGPUBufferMapAsyncStatus for different failures. The pattern used elsewhere looks more like a generic Error enum value + a `const char * message`. Should mapAsync change to that?

**Comment by kainino0x** [comment]
- see also #209
- (discussion)
- **Replace all of the validation cases with a single Validation value, add an error string like the other callbacks**

**Comment by kainino0x** [comment]
Actually, MapAsync is a little different from others in that it has _two_ error types in the JS spec, OperationError and AbortError. I think these need to be two different values in the enum.

**Comment by kainino0x** [comment]
We also need to actually pick names, for example:

- WGPUBufferMapAsyncStatus (or WGPUMapAsyncStatus)?
    - Success
    - InstanceDropped
    - Error or OperationError
    - Aborted or AbortError
    - Unknown

**Comment by lokokung** [comment]
FWIW, most of the other status codes all drop the object name:

`RequestAdapterStatus` vs `InstanceRequestAdapterStatus`
`RequestDeviceStatus` vs `AdapterRequestDeviceStatus`
`CompilationInfoRequestStatus` vs `ShaderCompilationInfoRequestStatus`
`CreatePipelineAsyncStatus` vs `DeviceCreatePipelineAsyncStatus`

The only ones that have the object name prepended (if I didn't miss any) are `BufferMapAsyncStatus` and `QueueWorkDoneStatus`.

**Comment by kainino0x** [comment]
May 23 meeting:


*   Add an equivalent for JS’s AbortError
*   Name of enum and enum values?
    *   KN: think “Error” / “Aborted” are good names
    *   **no objections**
*   Status type naming:
    *   LK: a lot of them drop the object name. \
AdapterRequestDevice → RequestDeviceStatus \
InstanceRequestAdapter –> RequestAdapterStatus \
proposal: \
BufferMapAsync → MapAsyncStatus
    *   CF / KN: sounds good me.
    *   LK: \
WGPUSurfaceGetCurrentTextureStatus\_Error → WGPUGetCurrentTextureStatus\_Error ? \
QueueOnSubmittedWorkDone → WorkDoneStatus ? OnSubmittedWorkDoneStatus ? QueueWorkDoneStatus ?
    *   **KN: Fine to rename buffer mapping one \
leave other ones for now**
    *   discussion about .yml generator, potentially nesting enums in some language bindings, like Buffer::MapAsyncStatus::Error
        *   KN: should be OK as long as it is _expressible_ in the yml that it _could_ be nested
        *   But yaml can specify how the name is spelled in all cases, don't have to derive it - like if there is a prefix or not, naming of QueueWorkDone
