### ISSUE TITLE
wrong return types for `wgpuBufferGetUsage` & `wgpuTextureGetUsage`

### ISSUE THREAD

**Issue by rajveermalviya** [webgpu-native/webgpu-headers#186]
return types for both should be `{type}Flags` types respectively, or `WGPUFlags` type [(if we want to strictly match the spec)](https://gpuweb.github.io/gpuweb/#dom-gputexture-usage).

```diff
- WGPU_EXPORT WGPUTextureUsage wgpuTextureGetUsage(WGPUTexture texture);
+ WGPU_EXPORT WGPUTextureUsageFlags wgpuTextureGetUsage(WGPUTexture texture);
```

```diff
- WGPU_EXPORT WGPUBufferUsage wgpuBufferGetUsage(WGPUBuffer buffer);
+ WGPU_EXPORT WGPUBufferUsageFlags wgpuBufferGetUsage(WGPUBuffer buffer);
```

**Comment by kainino0x** [comment]
This was also reported in #172 (I just was triaging issues yesterday so I remembered it was there). I'll see if we can get this fixed along with dawn so we don't accidentally regress it later.
