### ISSUE TITLE
GetMappedRange on READ-mapped buffer

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#194]
When a buffer is mapped for READ, GetConstMappedRange must be used to get a pointer. What happens if you use GetMappedRange? Dawn currently returns nullptr, but I think perhaps it should be invalid (e.g. crash on assertion in debug mode), for debuggability.

https://matrix.to/#/!ZSOHTEPDbwuEgSJwYw:matrix.org/$LHAITjEUC-TmB-YZ1des5TeUBO-FFRIvnZRfgfgbSZg?via=matrix.org

**Comment by kainino0x** [comment]
With or without that change, these could also be renamed as explicitly Read or ReadWrite. Though I like the current names personally.

**Comment by kainino0x** [comment]
In last week's meeting I think we settled on a proposal to:
- keep API surface as it is
- fail with an actual error string if you GetMappedRange on a READ mapping (see #143) or do anything else wrong (e.g. ask for an overlapping range, at least in Emscripten, see #64)

**Comment by kainino0x** [comment]
> * keep API surface as it is

Sorry I think I probably forgot to finish typing this sentence? the actual proposal adds some stuff to the API surface, and is here https://github.com/webgpu-native/webgpu-headers/issues/143#issuecomment-1612208345

**Comment by kainino0x** [comment]
We introduced the concept of "implementation-defined logging", which probably happened after the resolution above. I would prefer to use that here, and simply say "if there is an error, returns null and should log an error message to an implementation-defined log"

**Comment by lokokung** [comment]
+1 on using the implementation-defined logging for this to avoid the additional argument change. A validation error could also be a possible solution.

**Comment by eliemichel** [comment]
Couldn't the use of `wgpuBufferGetMappedRange` on a read-only mapped buffer trigger the device's uncaptured error callback? I remember doing this mistake a couple of time, and it always took me a bit more time to figure out my mistake than if the device's error callback would have been directly called to tell me "what you do makes no sense".

I believe this situation only occurs in case a programming error that should be solved by fixing the source code of the application, rather than something one wants to catch at runtime (but there can be edge cases I don't think about ofc).

**Comment by eliemichel** [comment]
All right following the JS API is important enough, no need to create an overload if there is clear enough logging :)

**Comment by kainino0x** [comment]
> We introduced the concept of "implementation-defined logging", which probably happened after the resolution above. I would prefer to use that here, and simply say "if there is an error, returns null and should log an error message to an implementation-defined log"

Oh, that actually is what we said we would do, I just couldn't find it: https://github.com/webgpu-native/webgpu-headers/issues/64#issuecomment-1710774712

Closing this as a duplicate of that issue.
