### ISSUE TITLE
Making device/resource destruction thread-safe requires locks in hot code

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#204]
I don't think we have an issue filed about this and apparently I forgot to file this when we talked about it. Anyway, in a webgpu.h standardization meeting we talked about the problem in the title. The proposal is:

- Make device/resource destruction an enableable feature (or two) (in native only), so that thread-safety locks can be skipped if the application doesn't use destroy().

It's apparently common to not need destroy() if you're in Rust or C++ (non-WASM), where your refs are getting dropped reliably (unlike JS which relies on garbage collection).

Marking has-resolution but input is still welcome!

This is a sub-issue of #184

**Comment by kainino0x** [comment]
Meeting:

We should have this be 2 features. If the feature is not enabled you get a validation error in the error scope.
You have to enable it even in WASM if you want to use it.

In WASM bindings, in order to implement this correctly you have to implement an extra layer on error scopes to inject errors - though to simplify, you can also just assert-crash if it's used and not enabled. If this proves to be difficult we might want to propose an injectError into the JS API. I think it's generally very useful for layering - for example if you wanted to polyfill a new WebGPU feature on old WebGPU features, you'd need this to do so correctly.

**Comment by kainino0x** [comment]
> You have to enable it even in WASM if you want to use it.

I forgot to mention this in the meeting but I think it's also possible for bindings to actually do the accounting for references between objects so it can automatically destroy() resources when their reference tree goes out of scope, just like you would have in native (that makes destroy() unnecessary in native). If we can achieve this then the API will still be usable in WASM without enabling this feature.

**Comment by Kangz** [comment]
> I forgot to mention this in the meeting but I think it's also possible/practical for bindings to actually do the accounting for references between objects so it can automatically destroy() resources when their reference tree goes out of scope, just like you would have in native (which is what makes destroy() unnecessary in native). 

I don't think that's correct, destroy() makes the resource immediately unusable in any future GPU timeline operation. Losing the last reference to a resource doesn't prevent using it, for example through an existing bindgroup or a texture view.

**Comment by kainino0x** [comment]
What I mean by references between objects is, the references from command buffers to bind groups, from bind groups to textures, etc. If we duplicate tracking of those references inside the WASM-JS bindings, then we can know there are no objects _referencing_ the texture, and nothing can be submitted which uses it, then we can destroy it.

**Comment by kainino0x** [comment]
Jan 25 meeting:

*   CF: wgpu no longer has a problem here. We have a single device-wide RW lock. If you have the R lock, you can use the resource. W lock only needed to destroy. So you can’t destroy while actively recording a command
*   KN: Not opposed to keeping it optional if it could have better performance
*   AE: Would prefer to have it be required - large difference from the JS API
    *   KN: But it’s only in the JS API because it’s GC
*   CF: Will probably have device destroy actively snatch and destroy everything. The one global lock means no cost to making everything snatchable
    *   KN: Destroy will block until everything else is done?
    *   CF: Pass encoder doesn’t hold the R lock. We just queue stuff up and only hold it during end(). The lock is only ever held inside a wgpu call.
    *   CF: Every function on the command encoder will take the lock. None of the functions in a render/compute pass encoder will.
*   **Overall leaning toward keeping destroy as enableable features because it is expected to be rarely used in many native languages**

**Comment by kainino0x** [comment]
Nov 21 meeting:

- KN: Corentin (Kangz) feels strongly that destroy should be left in core, not moved to an enabled feature, especially now that wgpu doesn't need it
- CF: Correct, not a problem anymore. OK making it core.
- **Make it core.**
