### ISSUE TITLE
Reporting DeviceLost in various functions and callbacks

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#209]
Currently we report DeviceLost in the following places aside from just the DeviceLost callback - places where the JS API does _not_ report it:
- MapAsyncStatus (see #183)
- CompilationInfoRequestStatus
- CreatePipelineAsyncStatus
- WorkDoneStatus
- PopErrorScope
- GetCurrentTextureStatus (after #203)

The JS API specifies generally that async operations pretend to work successfully after the device is lost (except for MapAsync): https://github.com/gpuweb/gpuweb/issues/1629#issuecomment-1664642751

Should we keep these DeviceLost enum values or should we do more like what the JS API does and pretend everything worked? Notably WASM can only do what JS does, so this makes it a native-only return value - but so are many of the others.

**Comment by Kangz** [comment]
We should probably match the JS API and pretend things worked.

**Comment by kainino0x** [comment]
*   (discussion)
*   **Remove the DeviceLost option everywhere**
*   including for MapAsync, return Unknown?
*   **Yes, remove it**
*   See also #183

**Comment by kainino0x** [comment]
> * including for MapAsync, return Unknown?

This changes to `Aborted` because that's what the upstream JS API does now.

**Comment by kainino0x** [comment]
This was done in #396 and #397.
