### ISSUE TITLE
Adding depthSlice to WGPURenderPassColorAttachment

### ISSUE THREAD

**Issue by austinEng** [webgpu-native/webgpu-headers#215]
This is getting added to core in the JS API.

Should we directly add it in these headers (no chained struct) given that we're not at the point of ABI stability yet?

**Comment by kainino0x** [comment]
IMO we should add it. Breaking changes are still coming to webgpu.h. Once we have stability we should decide. I would love if we could simply not provide ABI compatibility and only limited API compatibility (similar to how POSIX/Linux do it) but IDK if that will fly. The main compatibility problem with adding fields to structs later is that we can't enforce C applications zero-init their structs. That's pretty bad, so we may have to guarantee we don't add new fields.

**Comment by kainino0x** [comment]
FWIW for this particular feature it's not really known yet whether it's going to get landed in the JS spec before we stabilize webgpu.h, but that's ok, we can just include it anyway.

**Comment by kainino0x** [comment]
The upstream PR now distinguishes 0 from undefined, so we need an UNDEFINED macro here too.
