### ISSUE TITLE
Should more functions take extensible structs?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#216]
Struct chains provide extensibility to methods that take an extensible struct as an argument, like `CreateBuffer`. But there are a number of functions which don't. In JavaScript, all functions are extensible because we can add optional arguments to the end, but not in C.

Functions that could make sense to take extensible structs:

- WriteBuffer
- WriteTexture (EDIT: this used to take extensible structs but now it doesn't because those were shared with other functions and wouldn't extend cleanly)
- Submit
- OnSubmittedWorkDone
- GetCompilationInfo
- device Destroy
- EnumerateFeatures
- GetMappedRange/GetConstMappedRange
- MapAsync/Unmap
- PushErrorScope/PopErrorScope
- SetUncapturedErrorCallback
- ProcessEvents
- GetCurrentTexture (we said this was OK in #203)
- Present

These aren't extensible, but I don't think they need it:

- encoder commands
- Reference/Release
- FreeMembers
- buffer/texture/queryset Destroy
- SetLabel
- getters like GetWidth, GetBindGroupLayout, GetQueue
- Unconfigure

(I think that's the complete list)

**Comment by kainino0x** [comment]
*   Device destroy?
    *   KN: Could want an “emulate backend device loss”, could be a new function
*   encoder commands?
    *   CF: could definitely be extended
    *   KN: was thinking if that happens we just make a version 2 of the function
    *   CF: oh, only really need it in encoder creation
    *   KN: those are already extensible
*   …
*   KN: off the top of my head, I think the most likely to get extended are: \
Submit, ProcessEvents?, GetPreferredFormat, GetCurrentTexture?, Present

**Comment by Kangz** [comment]
MapAsync / Unmap for multi-queue as well.

**Comment by kainino0x** [comment]
meeting: discussed a little, but didn't conclude exactly which entry points we wanted to change. We want to add extensibility to at least some of them, so we can start with the easiest ones like GetPreferredFormat.

**Comment by kainino0x** [comment]
Note per #115 any function that takes an extensible struct needs to be able to return an error code if you pass something invalid in the struct chain.

**Comment by kainino0x** [comment]
> Likewise, should be have some form of both in and out extensibility for present? For example to request present timings.

_Originally posted by @Kangz in https://github.com/webgpu-native/webgpu-headers/issues/261#issuecomment-2315100082_

**Comment by kainino0x** [comment]
Sep 12 meeting:

- "should we have some form of both in and out extensibility for present? For example to request present timings."
- **Probably yes, and probably single pointer chain (not separate in chain and out chain; double check that this is consistent with other decisions)**

**Comment by kainino0x** [comment]
> * double check that this is consistent with other decisions

it's not; see https://github.com/webgpu-native/webgpu-headers/issues/261#issuecomment-1910889507

I'll keep thinking about this.

**Comment by kainino0x** [comment]
I was trying to get to implementing this, but it's a real pain due to the uncertainty about how different things will be extended.

I'd like to propose we not bother adding extensibility before we need it, and just introduce version `2` (or `Dawn`/`Wgpu` suffixed versions) of an entry point whenever we need to.

Part of the reason for this is that I don't want to create a bunch of structs that are empty except for a chain pointer. If we _do_ want to add chains now to any of these methods, we could avoid creating the empty structs by simply not defining them yet - declaring them opaquely so only `nullptr` can be passed - but that's super weird and unnecessary.

**Comment by kainino0x** [comment]
Dec 9 meeting:
* KN: (summary of last comment)
* **CF: OK**
