### ISSUE TITLE
WGPUTextureFormat_RGB10A2Uint is missing from WGPUTextureFormat

### ISSUE THREAD

**Issue by mwyrzykowski** [webgpu-native/webgpu-headers#226]
RGB10A2Uint was recently added to the WebGPU specification, but it appears missing from WebGPU.h under WGPUTextureFormat

We would like to propose adding it under WGPUTextureFormat.

**Comment by Kangz** [comment]
+1, we just added it in Dawn so it will be in the next batch of updates from Dawn API changes at the latest!
