### ISSUE TITLE
Render and Compute pass' timestampWrites is inconsistent with JavaScript API

### ISSUE THREAD

**Issue by eliemichel** [webgpu-native/webgpu-headers#227]
In a RenderPass or ComputePass descriptor, one can set up timestamp queries to write to at the beginning and/or end of the pass.

The **JS** API allows **at most a single timestamp write** at the beginning, and same at the end. Plus, both timestamp queries **must belong in the same QuerySet**:

```JavaScript
// JS API
dictionary GPUComputePassTimestampWrites {
    required GPUQuerySet querySet;
    GPUSize32 beginningOfPassWriteIndex; // optional
    GPUSize32 endOfPassWriteIndex; // optional
};

dictionary GPUComputePassDescriptor : /*[...]*/ {
    GPUComputePassTimestampWrites timestampWrites; // optional
};
```

The **C** API allows for much more: there can be as many writes as one wants (even though there is limited practical interest in writing twice the the same timestamp), and different writes may belong to different QuerySets.

```C
// Current C API
struct WGPUComputePassTimestampWrite {
    WGPUQuerySet querySet;
    uint32_t queryIndex;
    WGPUComputePassTimestampLocation location;
};

struct WGPUComputePassDescriptor {
    // [...]
    size_t timestampWriteCount;
    WGPUComputePassTimestampWrite const * timestampWrites;
};
```

Of course a **validation step** may ensure that only what the JS API supports is accepted, but IMHO it would make more sense (and be more didactic) to **structurally enfore** this constraint by mimicking more tightly the JS API:

```C
// Proposed C API
struct WGPUComputePassTimestampWrites {
    WGPUQuerySet querySet;
    WGPUComputePassTimestampLocationFlags writtenLocations;
    uint32_t beginningOfPassWriteIndex;
    uint32_t endOfPassWriteIndex;
};

struct WGPUComputePassDescriptor {
    // [...]
    WGPUComputePassTimestampWrites const * timestampWrites;
};
```

I see that the challenge in this port is to have the begin/end indices optional. Using `uint32_t const *` doesn't feel so satisfying for some reason so I put a "usage"-like flagfield `writtenLocations` to carry the boolean information of whether the index should be written to. (Also entries of the `WGPUComputePassTimestampLocation` enum have to switch to powers of 2.)

**Comment by Kangz** [comment]
The proposed C API works, and we could replace `WGPUComputePassTimestampLocationFlags` with a new macro `WGPU_QUERY_SET_INDEX_UNUDEFINED` set in one of the two indices, like in a couple other places in the API.

**Comment by eliemichel** [comment]
I agree @Kangz  that's actually much better!
