### ISSUE TITLE
Expand some bitmask enums to 64-bits?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#247]
Vulkan has had several bitmask enums that they had to expand from 32 bits to 64 bits (by adding version "2" of a bunch of things throughout the API like [VkPipelineStageFlags2](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineStageFlags2.html), vkCmdWriteTimestamp2). We should probably do this early to avoid that kind of thing.

We have 5 of these (in order of likelihood to need more than ~32~ 31? bits ever):
WGPUBufferUsage
WGPUTextureUsage
WGPUMapMode
WGPUShaderStage (almost certainly not)
WGPUColorWriteMask (definitely not)

Note that with #159 we're planning to remove the Flags typedefs, so all we would do here is change these enums' Force32 value to Force64.

---

- [ ] Probably document that native-only bits should be allocated in the 10-11 MSBs (because JS can only use 53 bits anyway). (Note: maybe don't use `2**63` if we use C enums if they're not guaranteed to be unsigned?)

**Comment by kainino0x** [comment]
Meeting:
- **Yes let's do this, let's just change all bitmask enums to 64-bits for consistency**

**Comment by kainino0x** [comment]
FWIW @toji pointed out to me today that the Web API will be limited to just 53 bits because everything passes through `double`. Still better than 32, though. Maybe if we have any native-only ones we can put them in the top 11 bits.

**Comment by toji** [comment]
And for the record, if we were ever backed into a corner where we absolutely HAD to have more than 53 bits in the WebAPI (which I see as somewhat unlikely?) , the most practical route would likely be to start passing them as arrays of JS enums:

```js
bufferUsage2: ['vertex', 'storage', 'copy-src', 'new-fancy-flag']
```

Not the worst thing in the world, but let's hope it never comes to that.
