### ISSUE TITLE
Consider renaming SwapChainSurface.suboptimal to optimal.

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#257]
A slight nit is that negative member names often end up creating double negations in code that are slightly harder to parse. Renaming `suboptimal` to `optimal` would help.

**Comment by kainino0x** [comment]
Meeting Jan 4:

*   Underlying APIs use “suboptimal”
*   CF: If the code is hard to read, make it an enum?
*   RM: Could add it to the existing status enum
*   KN: Does suboptimal only matter when the status is Success?
*   Yes
*   KN: A little annoying to check for both success and suboptimal statuses. Can we have a quicker way to see if you got a texture? Oh, we do - we return nullptr if you didn’t get one. Should document this.
*   **Merge into the status, and document that you don’t have to check the status if you just want to know if you got a texture.**

Something like:

```c
typedef enum WGPUSurfaceGetCurrentTextureStatus {
    WGPUSurfaceGetCurrentTextureStatus_SuccessOptimal = 0x00000000,
    WGPUSurfaceGetCurrentTextureStatus_SuccessSuboptimal = 0x00000001,
    WGPUSurfaceGetCurrentTextureStatus_Timeout = 0x00000002,
    // ...
} WGPUSurfaceGetCurrentTextureStatus WGPU_ENUM_ATTRIBUTE;

typedef struct WGPUSurfaceTexture {
    WGPUTexture texture;
    WGPUSurfaceGetCurrentTextureStatus status;
} WGPUSurfaceTexture WGPU_STRUCTURE_ATTRIBUTE;
```

*   GetCurrentTexture return structure
    *   Simplify?
        *   `WGPUTexture wgpuSurfaceGetCurrentTexture(WGPUSurface, WGPUGetCurrentTextureStatus* statusOutOptional);`
        *   optional status since you don’t necessarily need it if you just check for a null texture
        *   RM: Don’t think status pointer should be optional
        *   `WGPUTexture wgpuSurfaceGetCurrentTexture(WGPUSurface, WGPUGetCurrentTextureStatus* statusOut);`
        *   or flip it
        *   `WGPUGetCurrentTextureStatus wgpuSurfaceGetCurrentTexture(WGPUSurface, WGPUTexture* textureOut);`

Or `WGPUSurfaceTexture wgpuSurfaceGetCurrentTexture(WGPUSurface);`
I've filed #261 for more on this topic.

**Comment by eliemichel** [comment]
👍 For merging `suboptimal` into the status enum and specifying that the basic success test is `texture != nullptr`!
