### ISSUE TITLE
Using the WebGPU CTS as a test for Webgpu.h?

### ISSUE THREAD

**Issue by greggman** [webgpu-native/webgpu-headers#258]
Just a random idea. Would it be possible to make dawn-node just be dependent on webgpu.h? Then, multiple WebGPU.h implementations would easily have tests.

Of course they might also need tests for things that are specific to webgpu.h

**Comment by kainino0x** [comment]
The issue for this is #253. We discussed this idea a little bit, and the main problem is that we wouldn't be able to run it against the Emscripten implementation (we'd have to run Node inside WASM).

That said I would love for dawn-node to work portably on webgpu.h.
