### ISSUE TITLE
FreeMembers with struct chains

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#264]
Jan 11 meeting:

*   Should FreeMembers iterate down the struct chain for you, or should we have FreeMembers individually on each item in the chain?
*   discussion of how this works in a C++ API for example
    *   If C++ explicitly represents the chain, then is it OK if dropping the root of the chain frees the members of the rest of the chain?
    *   If C++ flattens all chained types into one struct, then it doesn’t matter except that the C++ bindings may have to make multiple FreeMembers calls in a row
*   ~**Tentatively it should iterate, but we don’t have any cases of this yet so TBD**~

**Comment by kainino0x** [comment]
A [question on Matrix chat](https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$5JImNgY-cVTpvfWlBaadE2hgAvgC1UpsxMUMF6Jo_jI?via=matrix.org&via=mozilla.org&via=kit.edu) about how to deal with this in C++ bindings (RAII) raised some issues:

- FreeMembers frees a bunch of arrays that are passed by pointer. Is it guaranteed to handle some/all of them being nullptr? I say "yes" because (1) length=0,ptr=null represents an empty array which could be a valid output of some function and (2) it shouldn't just work on those particular arrays being null, it should also work on "empty" (zeroed) structs.
- If no, wrappers _must_ avoid calling FreeMembers on zeroed structs. If yes, _should_ wrappers still try to avoid it? There is a tradeoff between:
  - complexity/time in the bindings, checking all of the arrays for null (recursively through the struct chain? [1])
    - The performance cost should be optimizable with inlining, but if the binding function is complex enough then it is less likely to get inlined. And bindings code complexity is annoying in its own right.
  - unnecessary calls into the C API
    - If the C API is dynamically linked or called by function pointer, then that is an unoptimizable cost.

  [1]: Recursing through the struct chain isn't required for anything right now but will probably eventually happen. OTOH if we reverse the tentative decision above and have FreeMembers for each struct in the chain (instead of one recursive one for the head struct), then each struct can be individually RAII'd, avoiding recursion. Then perhaps we can rely on compilers to inline+dead-code-eliminate the FreeMembers on default-initialized/moved-from structs.

**Comment by kainino0x** [comment]
cc @Kangz

**Comment by Kangz** [comment]
IMHO it should be "Yes" it handles it, as it makes it way simpler to use the API. I'm not concerned about slight overhead in `FreeMembers` or superfluous calls to it, because it should be mostly in the cold path.

**Comment by kainino0x** [comment]
FWIW, I didn't realize until recently, `free` and `delete` are guaranteed to no-op when passed a null pointer. So this is consistent with that.

**Comment by kainino0x** [comment]
> * Tentatively it should iterate, but we don’t have any cases of this yet so TBD

Some reasons to _not_ iterate - have a separate FreeMembers for each struct in the chain:
- Managing the lifetimes is less touchy, you don't have to keep the whole chain alive to call FreeMembers on the base
  - Any bindings which have RAII but explicit chaining (like Dawn's C++ bindings currently) will find it easy to call FreeMembers for each separately and can avoid worrying about the freeing order
- Extensions can just add FreeMembers for their extension structs and not for the base structs they chain off
  - With #395 this would also avoid adding FreeMembers to what used to be an input-only struct.

**Comment by kainino0x** [comment]
Dec 12 meeting:
* Should it be OK to pass a zero-initialized struct value (containing `nullptr`s) to `FreeMembers`?  
* **Yes.**

**Comment by kainino0x** [comment]
I realized this afternoon that making `FreeMembers` traverse the struct would also require `FreeMembers` to return a `WGPUStatus`.

**Comment by kainino0x** [comment]
Dec 19 meeting:

* KN: Realized we should actually make a decision on whether FreeMembers traverses the struct chain because if it does, it needs to return a `WGPUStatus`.  
* LK: Think FreeMembers should not traverse. Possible issues with user-allocated vs implementation-allocated in the same chain?  
* KN: Unlikely but maybe possible  
* CF: Agree may end up causing problems  
* **FreeMembers does not traverse**
