### ISSUE TITLE
wgpuAdapterGetProperties is sync but requestAdapterInfo is async

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#266]
_Originally posted by @beaufortfrancois in https://github.com/emscripten-core/emscripten/issues/21072#issuecomment-1904177995_

> I assume it's because of the async nature of it. All the code in this file using promises have callback while this one has not.

_Originally posted by @kainino0x in https://github.com/emscripten-core/emscripten/issues/21072#issuecomment-1905001256_

> Hm, right... I forgot that it was async in JS but sync in C.
> 
> I think to make this work we would need to have wgpuInstanceRequestAdapter actually do both requestAdapter AND requestAdapterInfo, then store off the results *in case* wgpuAdapterGetProperties is called later. I'm not sure if this is what we had in mind. It would work, but would make wgpuInstanceRequestAdapter slightly slower, and also would unnecessarily access fingerprintable info that the page may not actually need.
> 
> Alternatives would be:
> - Make it async in C
> - Somehow include in the wgpuInstanceRequestAdapter call whether you want to retrieve the properties or not

**Comment by beaufortfrancois** [comment]
Would it make sense to replace `wgpuAdapterGetProperties` with `wgpuAdapterRequestAdapterInfo` instead?

**Comment by Kangz** [comment]
> Somehow include in the wgpuInstanceRequestAdapter call whether you want to retrieve the properties or not

Seems sensible? At least in C it doesn't seem super necessary to keep the retrieval of info async.

**Comment by rajveermalviya** [comment]
Seems like this is something emscripten layer would have to workaround, because in the native it doesn't make sense to make it async, info callbacks can be especially annoying when enumerating adapters.

> and also would unnecessarily access fingerprintable info that the page may not actually need.

not sure how to avoid that

**Comment by kainino0x** [comment]
> > and also would unnecessarily access fingerprintable info that the page may not actually need.
> 
> not sure how to avoid that

That's the idea of "Somehow include in the wgpuInstanceRequestAdapter call whether you want to retrieve the properties or not": if you don't ask for it in RequestAdapterOptions, then we don't need to add the extra delay or the extra data access.

I think that's a pretty good option. Maybe it would look something like a new field in RequestAdapterOptions that's a bitfield with just 1 bit so far (0 = don't requestAdapterInfo(), 1 = do requestAdapterInfo()). Later on we might have extra bits to ask for more info.

**Comment by kainino0x** [comment]
Feb 1 meeting:

*   **Better to have it match the JS spec. Not too bad with promises**
*   Maybe propose to JS:
    *   1. Getter for the adapter info you currently have
    *   2. option to request info in requestAdapter
*   Could do this in C API without a JS spec change, but not necessary.

**Comment by beaufortfrancois** [comment]
Out of curiosity, what are the next steps?

**Comment by kainino0x** [comment]
Add WGPUAdapterRequestAdapterInfo to the C API (on our side, implement in Dawn) matching the usual patterns for async things. It will use futures, but we could have a stopgap version without futures if we really need one.

**Comment by beaufortfrancois** [comment]
Thanks! Here's https://github.com/webgpu-native/webgpu-headers/pull/269

**Comment by kainino0x** [comment]
> Add WGPUAdapterRequestAdapterInfo to the C API (on our side, implement in Dawn) matching the usual patterns for async things. It will use futures, but we could have a stopgap version without futures if we really need one.

Hm, I forgot we also wanted to remove wgpuAdapterGetProperties.
I also forgot WGPUAdapterProperties has extra info in it.
We'll need a proposal, I'm not sure if we want to move the extra info to an extension of WGPUAdapterInfo (how?) or keep GetProperties for this extra info (but as a native-only extension with no implementation in Emscripten)

**Comment by kainino0x** [comment]
Adding agenda label, but I'd like to get a proposal written down (from someone) before we discuss it.

**Comment by kainino0x** [comment]
Feb 1 meeting:

*   (brief discussion, sorry didn’t minute it)
*   **Better to have it match the JS spec. Not too bad with promises**
*   Maybe propose an addition to the JS API:
    *   1. sync getter for the adapter info you currently have
    *   2. option to request info in requestAdapter
*   Could do this in C API without a JS spec change, but not necessary to diverge.

**Comment by kainino0x** [comment]
Feb 15 meeting:

*   Previously we said we would just mirror the JS API into C for requestAdapterInfo. But in order to match we also need to do something about GetProperties. AdapterProperties has a few extra fields (vendorID, deviceID, adapterType, backendType).
    *   Remove GetProperties and move its extra data to some extension of RequestAdapterInfo?
    *   Keep GetProperties as a native-only extension? (with just those 4 fields?)
*   RM: Think we should make it an extension struct
*   KN: If it’s an extension on a struct passed to the callback, then it will create a backward-compat risk because applications need to handle chained struct types they don’t know about.
*   …
*   LK: Have the application pass the chained struct into RequestAdapterInfo, and have the callback just tell you it’s done?
*   KN: Yeah, probably better. I think we had an open issue about this, not sure what happened to it. We should make any other similar cases do the same thing. I should go through and check if there are others.
*   RM: Requires FreeMembers on those structs.
    *   (not a problem. we already have this, as AdapterPropertiesFreeMembers)

**Comment by kainino0x** [comment]
> * I should go through and check if there are others.

It is also a problem for GetCompilationInfo, which is more complicated because both WGPUCompilationInfo and WGPUCompilationMessage are extensible. Filed #272

**Comment by kainino0x** [comment]
The API that I think we came to for AdapterInfo - I took some liberties in filling in details, in particular moving backendType and adapterType to the core struct because it's sometimes possible to populate them in Wasm.

```c
typedef struct WGPUAdapterInfo {
    WGPUChainedStructOut * nextInChain;
    char const * vendor;
    char const * architecture;
    char const * device;
    char const * description;
    // Wasm can always tell you this, it's WGPUBackendType_WebGPU
    WGPUBackendType backendType;
    // Wasm may occasionally know this (e.g. if forceFallbackAdapter=true). Otherwise Unknown.
    WGPUAdapterType adapterType;
} WGPUAdapterInfo WGPU_STRUCTURE_ATTRIBUTE;

// Chains off WGPUAdapterInfo
typedef struct WGPUAdapterInfoVendorDeviceID {
    WGPUChainedStruct chain;
    uint32_t vendorID;
    uint32_t deviceID;
} WGPUAdapterInfoNative WGPU_STRUCTURE_ATTRIBUTE;

// Note WGPUAdapterInfo is not passed here at all.
typedef void (*WGPUAdapterRequestAdapterInfoCallback)(WGPU_NULLABLE void * userdata) WGPU_FUNCTION_ATTRIBUTE;

// (This will still change for the WGPUFuture refactor.)
WGPU_EXPORT void wgpuAdapterRequestAdapterInfo(WGPUAdapter adapter, WGPUAdapterRequestAdapterInfoCallback callback, WGPU_NULLABLE void * userdata) WGPU_FUNCTION_ATTRIBUTE;
```

WGPUAdapterInfoVendorDeviceID's SType would be in the 0x0001_xxxx range: https://github.com/webgpu-native/webgpu-headers/issues/214#issue-1855536975

**Comment by kainino0x** [comment]
I forgot the FreeMembers function for WGPUAdapterInfo:
```c
WGPU_EXPORT wgpuAdapterInfoFreeMembers(WGPUAdapterInfo adapterInfo) WGPU_FUNCTION_ATTRIBUTE;
```

**Comment by kainino0x** [comment]
Oops, I think I messed up wgpuAdapterRequestAdapterInfo too. It was supposed to take a pointer to a WGPUAdapterInfo allocated by the caller.

**Comment by Kangz** [comment]
I was chatting with @beaufortfrancois about implementations difficulties with the latest proposal and IMHO we should backtrack and go with something simpler.

My understanding is that we got to the current proposal because we wanted to have an API that mirrored the asynchronous nature of the JS API, but also made the developers build the chain that's filled by webgpu.h so that they control exactly what's in the chain. However the fact that the chain is allocated by the user before starting the async call makes it both hard to use the API correctly, and implement it correctly, because of complex lifetimes involved.

Instead my suggestion would be to go back to some form of:

```
bool wgpuAdapterGetAdapterInfo(adapter, WGPUAdapterInfo* adapterInfo);
```

In native implementation (remoting or not), the adapter info is known when we get the answer to `wgpuInstanceRequestAdapter` so things are ok. When targeting WebAssembly we could do `requestAdapter + requestAdapterInfo` before resolveing the `WGPUFuture`. If we worry about getting a prompt, in the future we could add a `requestInfo: bool` or a special `wgpuAdapterRequestAdaoterInfo(callback, userdata)` and have `wgpuAdapterGetAdapterInfo` return false and not fill anything if that `WGPUFuture` is not resolved.

**Comment by kainino0x** [comment]
That's a fair criticism. Without using WaitAny it means you always have to allocate the WGPUAdapterInfo and its chain on the heap. With WaitAny it could be on the stack but it's still tricky to use correctly.

> If we worry about getting a prompt, in the future we could add a `requestInfo: bool`

We won't add a prompt by default to the shipped API, but if we don't have a `requestInfo: bool` then we still access fingerprintable info that we don't necessarily need. I'm not sure how much of a problem this is but would like to avoid it.

> a special `wgpuAdapterRequestAdapterInfo(callback, userdata)` and have `wgpuAdapterGetAdapterInfo` return false and not fill anything if that `WGPUFuture` is not resolved.

I prefer this one for being closer to the JS API (it allows you to request adapter info after creation).

Note it could even work together with a `requestInfo: bool`, but that would just be a convenience. I don't think we should add it to the C API unless JS adds it.

So that proposal would be:

```
// (same structs as above)

WGPU_EXPORT wgpuAdapterInfoFreeMembers(WGPUAdapterInfo adapterInfo) WGPU_FUNCTION_ATTRIBUTE;

typedef void (*WGPUAdapterRequestAdapterInfoCallback)(
    WGPU_NULLABLE void * userdata) WGPU_FUNCTION_ATTRIBUTE;

WGPU_EXPORT void wgpuAdapterRequestAdapterInfo(WGPUAdapter adapter,
    WGPUAdapterRequestAdapterInfoCallback callback, // [1]
    WGPU_NULLABLE void * userdata) WGPU_FUNCTION_ATTRIBUTE;

WGPU_EXPORT void wgpuAdapterGetAdapterInfo(WGPUAdapter adapter,
    WGPUAdapterInfo * adapterInfo);
```

[1] Side note, we could even allow a null callback because it would receive no important args... just successfully waiting (or polling) the future would guarantee that GetAdapterInfo would start working.

**Comment by kainino0x** [comment]
(Unfortunately this doesn't make CompilationInfo in #272 any easier)

**Comment by Kangz** [comment]
The proposal above looks good, and in native/wire I believe the `wgpuAdapterRequestAdapterInfo` wouldn't need to be called. Also aren't getters supposed to return a `WGPUBool`?

**Comment by kainino0x** [comment]
Oh yes, right, I copied yours with the bool and deleted the wrong one. (Later will become a WGPUStatus or whatever)

**Comment by kainino0x** [comment]
Feb 29 meeting:

*   (Offshoot of [#266](https://github.com/webgpu-native/webgpu-headers/issues/266) but more generally - includes GetCompilationInfo too)
*   KN: (explanation of problem) CompilationInfo is extensible but also holds a
*   AE: RequestAdapterInfo/GetAdapterInfo are now more like MapAsync where it
*   …
*   RM: We need a pattern to request additional info anyway
*   KN: Think this is the only one that currently needs it
*   LK: A parallel array with the same indices in the CompilationInfo chain?
*   (take the chain out of the CompilationMessage)
*   LK: What if not every message has the same chain?
    *   KN: Can make it nullable somehow
*   How would this look? RequestCompilationInfo + GetCompilationInfo?
    *   Compilation info already lives forever (with the shader module) but in the wire we would be holding a _second_ copy alive (on the client side)
*   (discussion)
*   **OK with removing extensibility from CompilationMessage**
*   (discussion of doing the previous proposal for AdapterInfo)
*   KN: Not the worst if we say applications need to handle chain structs they don’t know about. (If we do that then CompilationMessage can be kept as extensible.)
*   LK: Would need a way to request which AdapterInfo extensions you want anyway
    *   Bitmask? Enum array? Dummy “prototype” struct chain?
    *   AE: Prefer array
        *   RM: agree, array of sTypes rather than creating new bitmasks
*   — out of time —
*   AE/KN offline: If we have a list of requests then actually applications will never get chains they don’t understand. This should work for both AdapterInfo and CompilationInfo.
    *   The list could be STypes, or it could be a new enum specific to the request
*   **KN will write up a proposal on GitHub**

**Comment by kainino0x** [comment]
Posted a different proposal on https://github.com/webgpu-native/webgpu-headers/issues/272#issuecomment-1971946124.
I think we'll continue the discussion there so we can design both together.

**Comment by kainino0x** [comment]
A few more thoughts for now.

- If we do end up adding a bit of info to the `requestAdapterInfo` call in JS, it may just be one bit ("allow permission prompt"), hence it wouldn't have lined up with the `allowedSTypes` array discussed in #272 like I thought it would. One more point against the `allowedSTypes` proposal.
- I remembered that if we are thinking about the browser measuring the amount of fingerprint bits the page has accessed, then actually the `requestAdapterInfo` call is irrelevant, what actually matters is *which attribute getters of `GPUAdapterInfo` are called*.
  - I filed #279 about this problem generally.
  - I think the thing I said before about calling `requestAdapterInfo` in Wasm `RequestAdapter` was wrong:
    > would unnecessarily access fingerprintable info that the page may not actually need

    This means we could simplify by calling JS `requestAdapterInfo` unconditionally when creating an adapter and just providing `GetAdapterInfo`.
  - If we did getters they could be simplified by flattening `GPUAdapterInfo` into `GPUAdapter`, putting the 4 getters on `GPUAdapter`.
  - We could alternatively pass a bitmask into `GetAdapterInfo` (or if we don't add that, then into `RequestAdapterInfo`) with one bit per field, so the Wasm bindings only have to access the fields requested.

**Comment by kainino0x** [comment]
Mar 7 meeting:

*   Should we do the proposal of making this synchronous in C by calling .requestAdapterInfo inside wgpuInstanceRequestAdapter?
    *   Seriously considering it, but doesn’t match JS API.
*   Should we try to fix the JS API?
    *   **Yes. Go propose it.**

**Comment by kainino0x** [comment]
I haven't gotten around to opening a proposal yet but the gist is add the adapter info as adapter.adapterInfo or adapter.getAdapterInfo(). If there's a way to get adapter info without a prompt, then IMO there's no reason it needs to be async. We don't need async in order to dynamically decide what to expose / measure what we've exposed; properties on GPUAdapterInfo are already getters.

**Comment by kainino0x** [comment]
https://github.com/gpuweb/gpuweb/issues/4536

**Comment by kainino0x** [comment]
Mar 28 meeting:

*   JS API folks were OK with a sync API, so opened a PR and expecting it to be approved
*   **No problem here**

**Comment by kainino0x** [comment]
> * JS API folks were OK with a sync API, so opened a PR and expecting it to be approved

(And we can always do the requestAdapterInfo-in-wgpuInstanceRequestAdapter trick regardless of whether it is.)

Actual design depended on #279, but that's resolved now too, so we need a proposal. Most likely we just make it look like GetProperties but restructure as needed.

**Comment by kainino0x** [comment]
I think we reuse the structs and FreeMembers definitions proposed above, and the getter is simply as Corentin wrote it:

```c
WGPU_EXPORT WGPUStatus wgpuAdapterGetInfo(WGPUAdapter adapter,
    WGPUAdapterInfo *info) WGPU_FUNCTION_ATTRIBUTE;
```

or "GetAdapterInfo". I've proposed `info` in the JS API but it could be bikeshedded; we should try to match it.

**Comment by kainino0x** [comment]
```c
typedef struct WGPUAdapterInfo {
    WGPUChainedStructOut * nextInChain;
    char const * vendor;
    char const * architecture;
    char const * device;
    char const * description;
    // Wasm can always tell you this, it's WGPUBackendType_WebGPU
    WGPUBackendType backendType;
    // Wasm may occasionally know this (e.g. if forceFallbackAdapter=true). Otherwise Unknown.
    WGPUAdapterType adapterType;
    // Vendor/device ID are zero if you can't get them (like on Wasm)
    uint32_t vendorID;
    uint32_t deviceID;
} WGPUAdapterInfoVendorDeviceID WGPU_STRUCTURE_ATTRIBUTE;

WGPU_EXPORT wgpuAdapterInfoFreeMembers(WGPUAdapterInfo adapterInfo) WGPU_FUNCTION_ATTRIBUTE;

WGPU_EXPORT WGPUStatus wgpuAdapterGetInfo(WGPUAdapter adapter,
    WGPUAdapterInfo *info) WGPU_FUNCTION_ATTRIBUTE;
```

**Comment by kainino0x** [comment]
Apr 11 meeting:


*   Need to figure out the API shape
*   CF: How do you know if you can use the VendorDeviceID chain?
    *   KN: Hm, didn’t propose an instance feature for this…
        *   AE: or adapter feature
    *   Need one?
    *   Not worth it, probably just bake it into the main struct
*   AE: what about fingerprinting and JS checking what properties you access?
    *   KN: conclusion was: probably doesn’t matter for any C program from web assembly - because they’re going to do actual real work, so we probably have to assume they know everything that we would expose in the adapter info anyway
        *   architecture, from draw/compute results
        *   limits, from validation results
    *   **Inline the vendor/device id**
*   **code just posted looks good**

**Comment by beaufortfrancois** [comment]
Shall we close this issue?

**Comment by kainino0x** [comment]
Yes, I think so. Thanks!
