### ISSUE TITLE
Format Capabilities

### ISSUE THREAD

**Issue by austinEng** [webgpu-native/webgpu-headers#283]
This request most immediately is coming because Chrome is using Dawn as well as the rest of the graphics system, and needs to know the drmFormatModifiers for a particular format - effectively calling `vkGetPhysicalDeviceFormatProperties2` under the hood.

It occurs to me, we could split this into two separate concepts if that's desirable. At a high level:
 1. Querying capabilities of formats as it relates external to the WebGPU API - like DRM format modifiers
 2. Querying capabilities of formats as it relates to the WebGPU API itself - can I use it as a render attachment, storage, etc.
 
We've touched on (2) in the API spec in the past as a way of having fine-grained queries (and ability to enable?) what a format can be used for - instead of relying on knowing what the spec says, or checking the `bgra8unorm-storage`, `formats-tier-1`, `formats-tier-2`, etc. So I'm pulling that into this discussion. Because if we ever do add a way to query these capabilities, we should have it and the DRM thing be compatible.

Tentative proposal:

```c

struct WGPUFormatCapabilities {
  WGPUChainedStructOut * nextInChain;
  // nothing here!
  // add capabilities from core webgpu ??
};

struct WGPUFormatCapabilitiesDRM {
  WGPUChainedStructOut chain;
  uint32_t* modifiers;
  size_t modifierCount;
};

void wgpuAdapterGetFormatCapabilities(WGPUAdapter, WGPUFormat format, WGPUFormatCapabilities* capabilities);

typedef enum WGPUFeatureName {
  ...
  WGPUFeatureName_FormatCapabilities, // new enum
  WGPUFeatureName_FormatCapabilitiesDRM, // new enum
  ...
};

```

- It's invalid to query DRM format capabilities if the adapter does not support the feature.
- it's also in valid to query the base struct if you don't have `WGPUFeatureName_FormatCapabilities` - even though it's entirely empty. The expectation is that we could put core webgpu things here at some point. If we don't, we can also remove the requirement to have `WGPUFeatureName_FormatCapabilities` and it would be a non-breaking change.
- The return value for `wgpuAdapterGetFormatCapabilities`  should be an enum which says you did an invalid thing if it's not supported. But we haven't implemented those changes yet.
  See https://github.com/webgpu-native/webgpu-headers/issues/115#issuecomment-1710833736
- It's a little weird if the base `WGPUFormatCapabilities` is entirely empty. An alternative is to remove it entirely and have only `wgpuAdapterGetFormatCapabilitiesDRM`. This doesn't play nicely if we add more capabilities in the future.  Another option is to have the signature be `void wgpuAdapterGetFormatCapabilities(WGPUAdapter, WGPUFormat format, WGPUChainedStructOut* capabilities);` where you only pass an extension chain - but this is a little odd IMO.
- Should the query of capabilities be on the `WGPUDevice` instead of the `WGPUAdapter` ? This is relevant if for example you enable some feature on the device `formats-tier-2` or `bgra8unorm-storage`. It could impact the format capabilities that an application queries.

**Comment by khaslettgoogle** [comment]
Here is my WIP change to add the API roughly as described above: https://dawn-review.googlesource.com/c/dawn/+/179080

I think putting the DRM version behind a feature certainly makes sense since it's only meaningful on Linux platforms.

It seems reasonable to me that the base WGPUFormatCapabilities struct is empty for now, and could be populated in the future behind a WGPUFeatureName_FormatCapabilities feature as you describe.

> Should the query of capabilities be on the WGPUDevice instead of the WGPUAdapter ? 
At least in the DRM case my feeling is that this should be on the WGPUAdapter, as it's only dependent on the physical device you're using. If there are properties that do depend on the device you're using perhaps those should be separate APIs on the WGPUDevice?

**Comment by austinEng** [comment]
That's interesting - I didn't think about having it both on Adapter and on Device, but yea that would be reasonable.

I'll update the top comment to reflect always having WGPUFeatureName_FormatCapabilities.

**Comment by austinEng** [comment]
Closing this since it's Dawn-internal for now. Can reopen if we want to make it common.
