### ISSUE TITLE
WGPUTextureDataLayout name doesn't match WebIDL GPUImageDataLayout

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#286]
WGPUTextureDataLayout is called GPUImageDataLayout upstream (EDIT: and we have WGPUImageCopyBuffer and WGPUImageCopyTexture already in C). Probably they should match.

Note, we don't use the "image" language anywhere in the stable JS API though - only in dictionary names - so the upstream WebIDL can still be changed (I think). "Image" is kind of a confusing word; the naming deserves some more attention before it becomes part of a stable API.

**Comment by Kangz** [comment]
+1 for calling it `WGPUImageDataLayout`. The term image in the JS spec seems to refer to how pixels are laid out in linear memory for a single miplevel/aspect while the term texture is for the full breadth of non-linear memory things.

**Comment by kainino0x** [comment]
Yes, we chose that naming in the JS spec intentionally to be different from "Texture" to refer to this concept. But I am still interested to see if we could come up with a clearer name than "Image", because that has overlap with Vulkan, `new Image()`, etc.

Apr 11 meeting:

*   (discussion)
*   CF: Two things
    *   native should match the JS spec’s naming
    *   we should poke the JS spec to reconsider this naming
*   **Tentatively rename to WGPUImageDataLayout but also see what editors say on Monday**

**Comment by kainino0x** [comment]
https://github.com/gpuweb/gpuweb/issues/4573

**Comment by kainino0x** [comment]
I finally landed an upstream rename! https://github.com/gpuweb/gpuweb/pull/4838
