### ISSUE TITLE
Is `wgpuSurfaceGetPreferredFormat` redundant with `WGPUSurfaceCapabilities.formats[0]`?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#290]
Since @beaufortfrancois is trying to port some samples, I realized we probably should list the preferred format as `formats[0]`. Otherwise it's not obvious that `formats[0]` might give you the wrong format and you need to call `GetPreferredFormat` instead.

`GetPreferredFormat` is already planned to become extensible (https://github.com/webgpu-native/webgpu-headers/issues/216) so it can take extra options into account unlike `formats[0]`, but in the near term it won't actually have any extra options, so maybe there's no reason to have it at all yet. We can add the function once it actually has extra options.

**Comment by Kangz** [comment]
I'd definitely be in favor of removing it for now!

**Comment by kainino0x** [comment]
After reviewing some code using this, I do think it's a little bit of a magic incantation to use `formats[0]` to get the preferred format. But probably not a big deal.

**Comment by kainino0x** [comment]
May 23 meeting (sorry for delay):


*   AE/KN: Both in favor of doing this
*   CF: me too
*   KN: eventually JS spec may have srgb, hdr, etc.
*   AE: Can you get this information by just filtering and looking for first match?
*   KN: Probably? If you filter to a format that you need, then the first one you get should be the preferred one? Could use this as a basic heuristic?
*   AE: What about WASM? Would we get only the JS-allowed format?
*   KN: Yea, but there’s 3 formats, so ordering would tell us what's the preferred one.
*   **Remove wgpuSurfaceGetPreferredFormat, formats[0] is preferred.**

**Comment by yig** [comment]
If `wgpuSurfaceGetPreferredFormat()` is coming back with an extra options struct, perhaps it can be left in place with a placeholder nullable `WGPUSurfaceGetPreferredFormatOptions` struct parameter? It is much more pleasant to write

```
    .format = wgpuSurfaceGetPreferredFormat( surface, adapter, nullptr ), // Sokol-style designated initializer
```

versus

```
WGPUSurfaceCapabilities capabilities;
wgpuSurfaceGetCapabilities( surface, adapter, &capabilities );
something.format = capabilities.formats[0];
wgpuSurfaceCapabilitiesFreeMembers( capabilities );
```

**Comment by Kangz** [comment]
Done in #319.
