### ISSUE TITLE
Should WGPUSurfaceCapabilities.alphaModes include Auto?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#292]
`WGPUSurfaceCapabilities.alphaModes` lists the supported `WGPUCompositeAlphaMode`s, out of:

```c
typedef enum WGPUCompositeAlphaMode {
    WGPUCompositeAlphaMode_Auto = 0x00000000,
    WGPUCompositeAlphaMode_Opaque = 0x00000001,
    WGPUCompositeAlphaMode_Premultiplied = 0x00000002,
    WGPUCompositeAlphaMode_Unpremultiplied = 0x00000003,
    WGPUCompositeAlphaMode_Inherit = 0x00000004,
    WGPUCompositeAlphaMode_Force32 = 0x7FFFFFFF
} WGPUCompositeAlphaMode WGPU_ENUM_ATTRIBUTE;
```

I believe `Auto` is always "supported". Should it be listed in `alphaModes`?

Followup issue to #203. cc @rajveermalviya @Kangz @eliemichel

**Comment by kainino0x** [comment]
If we don't list it, then I think `alphaModes[0]` should be the same as whatever `Auto` would pick (either `Opaque` or `Inherit`).

**Comment by kainino0x** [comment]
Jun 6 meeting:


*   should do the same thing as formats. there is no preferred format, use formats[0]
*   no need to report Auto, it is always supported
*   could also be helpful to know what Auto is going to map to..?
*   CF: You don’t know what the default is on the system.
    *   KN: In a native app, you would use Inherit. When you’re targeting web, you use Opaque because Inherit doesn’t exist (or we make it so Inherit means Opaque on web, but probably not). But, in order to use Inherit, you have to know what it is (in native you’ll have set it up somewhere else). If it’s the wrong thing, it’s not going to work.
    *   CF: The impression of Inherit I get is that you don’t care. You just want something.
    *   KN: Right, if you’re always clearing the alpha channel, all modes do the same thing.
    *   CF: which is most applications - you don’t actually care.
    *   KN (+ clarifications): So should we [replace Inherit with] a mode that is “assume alpha is 1”? Or is Inherit meant to also be usable with externally-configured transparency modes?
        *   discussion: think inherit can be used with transparency
    *   …
*   AE: For the question of whether to return auto, I guess don’t return it? doesn’t seem useful
*   KN: As long as we’re able to say what Auto maps to for alphaModes[0], then it’s ok.	
    *   If we put Auto first, then the rest of the list can be unsorted. alphaModes[1] doesn’t have to be anything in particular
*   **Don’t return Auto in alphaModes array, alphaModes[0] is always equivalent to Auto**

**Comment by Kangz** [comment]
Done in #319.
