### ISSUE TITLE
Using fixed-length arrays for some output arrays?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#302]
In Emscripten there were a few suggestions to use fixed-length arrays for some outputs to avoid needing FreeMembers. In particular AdapterInfo just has a few strings in it - we _probably_ could get away with setting some fixed limit on their size, but `description` is the most unsure, since it might get wrapped repeatedly the way ANGLE does:
`ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Version 14.5 (Build 23F79))`

Discussion was here: https://github.com/emscripten-core/emscripten/pull/22031#discussion_r1624954986

**Comment by Kangz** [comment]
Do we know what the cost of a malloc is in emscripten? Something like `AdapterGetInfo` happens maybe once per application run so it doesn't seem super worth optimizing by having some arbitrary length hardcoded.

**Comment by kainino0x** [comment]
I'm definitely not concerned with the performance cost for AdapterGetInfo, given it should be called basically once. It's more of an ergonomic improvement as you wouldn't need FreeMembers at all for this struct. It's feasible to do similar things for other structs as well, like changing `presentModes` to a fixed-size array.

**Comment by Kangz** [comment]
Ah, that would be a problem only for C though and only in a few places so not super important either imho.

**Comment by kainino0x** [comment]
* e.g. `char vendor[256]`, instead of `char const * vendor` \+ `FreeMembers`  
* CF: Seems like an over-optimization  
* KN: Think it would more of an ergonomic improvement than anything  
* CF: Prefer to have consistency since some places will need FreeMembers  
* **Leave as is**
