### ISSUE TITLE
Should GetProcAddress take a WGPUStringView?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#351]
Sub-issue of #170:
> - (input) GetProcAddress??

I was documenting `wgpuGetProcAddress` (#349) and noticed it takes a null-terminated C string rather than a `WGPUStringView`.

We said we would replace ~all of the instances of strings in the API with WGPUStringView, but I'm not sure whether that should apply to this, since it's kind of C-specific?

**Comment by kainino0x** [comment]
@Kangz since you probably have a bit better idea what real usage of EGL's GetProcAddress looks like

**Comment by Kangz** [comment]
I think we should replace it, there isn't really a drawback to doing it. All the `GetProcAddress` take a C string usually, but this would just be a matter of doing `wgpuGetProcAddress({myString, WGPU_STRLEN})` so it's not much worse.

**Comment by kainino0x** [comment]
I'll consider "has resolution" then since it fits with our plan to replace all string pointers with StringViews.
