### ISSUE TITLE
popErrorScope status when stack is empty?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#369]
In JS when the error scope stack is empty, popErrorScope rejects with OperationError. What should we do in C?

Emscripten and Dawn currently translate it to `Unknown` plus a message string. However we also use `Unknown` in Emscripten if the error type is some unexpected object (e.g. if we add one to the JS API in the future).

We should also say what the message string is. I think it **must** be empty if the status is NoError and it **should** be non-empty for any other status. (since message can't be null anymore)

**Comment by lokokung** [comment]
Hmm, that's a good point. In C, there's only `Success` and `InstanceDropped` on `WGPUPopErrorScopeStatus`. Maybe we could add another case there instead of modifying the error type?

**Comment by kainino0x** [comment]
You're right, using the status makes more sense. Also, we shouldn't add it to `WGPUErrorType`, since that's also used in `WGPUUncapturedErrorCallback`.

We have to decide what values you get when the status is something other than `Success`.
- `WGPUStringView message` is empty string
- `WGPUErrorType type` is... `NoError=1`? `Unknown=5`? Add a new `Undefined=0` and return that? Renumber `NoError` to `0`? Rename `NoError=1` to `Undefined=0` and return that?

The first half of this seems pretty trivial so I'm going to just open a PR for it.

**Comment by kainino0x** [comment]
It should not be `Unknown` because that value implies there will be a `message` string.

**Comment by kainino0x** [comment]
Tentatively closing as I did my proposal in #393, but leaving the label to discuss if we want to reopen.

**Comment by kainino0x** [comment]
Nov 21 meeting:

*   KN: This is a promise rejection in JS. I already added `WGPUPopErrorScopeStatus_EmptyStack` (in addition to `Success` and `InstanceDropped`.
    *   (we can't add it to `WGPUErrorType`, that's also used in `WGPUUncapturedErrorCallback`)
*   **Sounds good**
*   When the status is `EmptyStack` or `InstanceDropped`, what should `WGPUErrorType type` be? I tentatively said `NoError` since that matches with `message` being empty string.
*   **NoError because you captured no error (it's always the case that status==Success || type=NoError). But change string to be allowed to be non-empty? (The string is dual purpose: EITHER the error from the status OR the error from the captured error)**
*   **Rename EmptyStack to Error or ValidationError or something**
