### ISSUE TITLE
Status enums still have too many values

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#401]
Following on #396 we should check if there are any other extraneous status values. Checked box = definitely good, or we decided what to do about it.

These look good:

- WGPUPopErrorScopeStatus
  - [x] WGPUPopErrorScopeStatus_Success
  - [x] WGPUPopErrorScopeStatus_InstanceDropped

- WGPUErrorType (not really a status but we'll include it)
  - [x] WGPUErrorType_NoError
  - [x] WGPUErrorType_Validation
  - [x] WGPUErrorType_OutOfMemory
  - [x] WGPUErrorType_Internal
  - [x] WGPUErrorType_Unknown - this is a bit niche but it's used if the browser returns some new status code and Wasm bindings don't understand it and need to translate it into a WGPUErrorType. It could be renamed/renumbered to `Undefined=0` but I don't think there's any real reason to do that.

- WGPUAdapterType (this really isn't a status but it also has an "unknown")
  - [x] WGPUAdapterType_Unknown - this could also be renamed/renumbered to `Undefined=0`

- WGPUDeviceLostReason (also not technically a status) (see also https://github.com/webgpu-native/webgpu-headers/issues/299#issuecomment-2469381621)
  - [x] WGPUDeviceLostReason_Unknown - this is from the JS spec
  - [x] WGPUDeviceLostReason_Destroyed
  - [x] WGPUDeviceLostReason_InstanceDropped
  - [x] WGPUDeviceLostReason_FailedCreation

- WGPUWaitStatus
  - [x] WGPUWaitStatus_Success
  - [x] WGPUWaitStatus_TimedOut
  - [x] WGPUWaitStatus_UnsupportedTimeout
  - [x] WGPUWaitStatus_UnsupportedCount
  - [x] WGPUWaitStatus_UnsupportedMixedSources

These I'm not sure about:

- WGPURequestAdapterStatus
  - [x] WGPURequestAdapterStatus_Success
  - [x] WGPURequestAdapterStatus_InstanceDropped
  - [x] WGPURequestAdapterStatus_Unavailable - presumably this is used when no adapter is available, but JS treats this as "success" and returns a null adapter. Should we really have a separate status for this? (Probably yes.)
    **Keep**
  - [x] WGPURequestAdapterStatus_Error (validation error)
  - [x] WGPURequestAdapterStatus_Unknown - Dawn uses this when there is a wire error. Should it return InstanceDropped, or pretend an adapter is unavailable instead? (or crash)
    **Remove**

- WGPURequestDeviceStatus
  - [x] WGPURequestDeviceStatus_Success
  - [x] WGPURequestDeviceStatus_InstanceDropped
  - [x] WGPURequestDeviceStatus_Error (validation error)
  - [x] WGPURequestDeviceStatus_Unknown - Dawn uses this when there is a wire error. Should it return InstanceDropped, or return a lost device instead? (or crash)
    **Remove**

- WGPUQueueWorkDoneStatus
  - [x] WGPUQueueWorkDoneStatus_Success
  - [x] WGPUQueueWorkDoneStatus_InstanceDropped
  - [x] WGPUQueueWorkDoneStatus_Error (validation error) - Happens when the queue is `invalid`. I don't think this is possible now; it will be, but should we keep this status in the meantime?
    **Remove**
  - [x] WGPUQueueWorkDoneStatus_Unknown - When would we use this instead of faking success? I don't think Dawn uses this. (Not sure what it does on wire errors.)
    **Remove**

- WGPUMapAsyncStatus
  - [x] WGPUMapAsyncStatus_Success
  - [x] WGPUMapAsyncStatus_InstanceDropped
  - [x] WGPUMapAsyncStatus_Error (validation error)
  - [x] WGPUMapAsyncStatus_Aborted
  - [x] WGPUMapAsyncStatus_Unknown - Dawn uses this when there is a wire error. Should it return InstanceDropped, or lose the device and return Aborted instead?
    **Remove**

- WGPUCompilationInfoRequestStatus
  - [x] WGPUCompilationInfoRequestStatus_Success
  - [x] WGPUCompilationInfoRequestStatus_InstanceDropped
  - [x] WGPUCompilationInfoRequestStatus_Error - there are no possible validation errors here unless we're validating the CallbackMode (which I think we're supposed to crash on when invalid). So what does this mean? I don't think Dawn uses this.
    **Remove**
  - [x] WGPUCompilationInfoRequestStatus_Unknown - when would we use this instead of Success or crashing? I don't think Dawn uses this. (Not sure what it does on wire errors.)
    **Remove**

- WGPUCreatePipelineAsyncStatus
  - [x] WGPUCreatePipelineAsyncStatus_Success
  - [x] WGPUCreatePipelineAsyncStatus_InstanceDropped
  - [x] WGPUCreatePipelineAsyncStatus_ValidationError
  - [x] WGPUCreatePipelineAsyncStatus_InternalError
  - [x] WGPUCreatePipelineAsyncStatus_Unknown - Dawn uses this when there is a wire error. Should it return InstanceDropped, or lose the device and return Success instead?
    **Remove**

- WGPUSurfaceGetCurrentTextureStatus
  - [x] WGPUSurfaceGetCurrentTextureStatus_SuccessOptimal
  - [x] WGPUSurfaceGetCurrentTextureStatus_SuccessSuboptimal
  - [x] WGPUSurfaceGetCurrentTextureStatus_Timeout
  - [x] WGPUSurfaceGetCurrentTextureStatus_Outdated
  - [x] WGPUSurfaceGetCurrentTextureStatus_Lost
  - [x] WGPUSurfaceGetCurrentTextureStatus_OutOfMemory - TBH not entirely certain how this would be used. I don't think Dawn uses this.
    **Remove probably**
  - [x] WGPUSurfaceGetCurrentTextureStatus_DeviceLost - already slated for removal in #397
  - [x] WGPUSurfaceGetCurrentTextureStatus_Error (validation error)

**Comment by kainino0x** [comment]
@lokokung you would know better what the wire is doing in the futures code, could you review the notes above?
@Kangz PTAL as well

**Comment by kainino0x** [comment]
Forgot the synchronous statuses WGPUWaitStatus and WGPUSurfaceGetCurrentTextureStatus. Added above.

**Comment by Kangz** [comment]
All `_Unknown` are used by Dawn wire when the connection drops, but we should instead pretend that all devices are lost similar to JS.

So my suggestion would be to keep just `WGPURequestAdapterStatus_Unavailable` for RequestAdapter failing to get an adapter, like when the instance is lost.

**Comment by lokokung** [comment]
IIRC, when the wire connection drops, the current implementation uses `InstanceDropped` for all the callbacks, including `RequestAdapter`. For wire errors, maybe we should generalize something like `Unrecoverable` and use that for `InstanceDropped` and other weird errors? Not sure..., but right now `InstanceDropped` is probably too specific of a name given that it's used in multiple scenarios, i.e. wire drop.

**Comment by kainino0x** [comment]
Dropping the wire is kind of like dropping the instance, in that you no longer really hold a reference to the (server-side) instance, except that it can happen outside of our control (e.g. server process crashes).

Losing the wire connection doesn't totally kill futures though, we still track them client side and can still pretend they succeed or whatever. So I think it makes more sense to do that rather than return InstanceDropped on disconnect?

**Comment by kainino0x** [comment]
Just a note, `WGPUErrorType` also has `Unknown` which could _maybe_ be called `Undefined=0` but I don't think there's any reason to do that. Same could be done for `WGPUAdapterType`.

**Comment by kainino0x** [comment]
Couldn't we just as well pretend they succeed just like we do on device loss, and call the callback with `Success`? (except for MapAsync which gets `Aborted`)

**Comment by lokokung** [comment]
Hmm, we could? But it'll be a silent failure since I think we said we wanted the `StringView msg` to be empty if we resolve with `Success` in most callbacks.

**Comment by kainino0x** [comment]
I think a silent failure makes sense. We do that on device loss, we just have another channel for reporting the device loss happened. Probably we would report device loss if the wire disconnects, too.

**Comment by kainino0x** [comment]
Dec 9 meeting:

* KN: "Unknown" statuses were used in Dawn for wire disconnection, those should presumably be either Success or InstanceDropped \- which one?  
  * CF: Probably fine, but @rajveermalviya would know if wgpu-native needs these  
  * But Dawn will probably try to remove, and that should prove it's logically possible  
* KN: RequestAdapter distinguishes "Success" from "Unavailable" whereas JS's `Promise<GPUAdapter>` just returns null if unavailable. Should we keep the enum distinction? Probably, why not.  
  * **Keep the distinction**, otherwise unclear (moreso than in JS). Also better in C++ because don't have to figure out how to check nullness.  
* KN: `WGPUQueueWorkDoneStatus_Error` is not possible because queues can't be invalid. Keep anyway for when we have multiqueue, or remove until then?  
  * **Remove**  
* KN: `WGPUCompilationInfoRequestStatus_Error` is not possible. Remove?  
  * **Remove**  
  * (if CallbackMode is invalid, that returns a null future, not an error status)
* KN: `WGPUSurfaceGetCurrentTextureStatus_OutOfMemory` \- when would this actually be used?  
  * CF: Swapchain ran out of memory for some reason. Whole world explodes? It does happen in wgpu.  
  * KN: Also weird because not possible to report in async context (e.g. wire) because it's synchronous.  
  * CF: Some places where we don't *really* know what happened and report out of memory. Surfaces very complicated though, especially Linux.   
  * KN: **Remove it from upstream header for now and wgpu can see if it can remove it, or just keep it as an extension?**  
  * CF: OK.  
  * LK: Could maybe return a message string? (Though requires a FreeMembers, or a static string.)
  * (... we didn't really discuss this much but I think we thought it wasn't worth it)

**Comment by kainino0x** [comment]
Opened two PRs for the remaining things, I'll just close this and use those to track work.

**Comment by lokokung** [comment]
Regarding WGPUQueueWorkDoneStatus_Error, we decided to backtrack and keep it since it may become relevant in the future.
