### ISSUE TITLE
WGPUProgrammableStageDescriptor is actually for compute only

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#409]
The thing called `WGPUProgrammableStageDescriptor` is only used in `WGPUComputePipelineDescriptor` because we have independent definitions for the vertex/fragment equivalents, that have their own module/entryPoint/constants (`WGPUVertexState` and `WGPUFragmentState`).

- Should it be flattened into `WGPUComputePipelineDescriptor`? (Future extensions would go there)
- If not:
  - Should `WGPUProgrammableStageDescriptor` be renamed to be compute-specific?
  - Or should vertex/fragment also use `WGPUProgrammableStageDescriptor`? (This would make it slightly more uniform to add extensions that apply to all three; but we can already do that by allowing that extension to have multiple base structs.)
  - Should both the parent and child struct still be extensible?

**Comment by Kangz** [comment]
+1 for renaming to `WGPUComputePipelineDescriptor`. IMHO it's overkill to make the C struct hierarchy match the JS dictionary hierarchy because it in C you'd need to have the parent as members, which makes the API more annoying to use. But also in JS we can easily add intermediate dictionaries any time, which would make webgpu.h no longer match the WebGPU API.

**Comment by kainino0x** [comment]
> +1 for renaming to `WGPUComputePipelineDescriptor`.

Do you mean flatten into `WGPUComputePipelineDescriptor`, or rename to something else like `WGPUComputeState` or `WGPUComputeStage`? (I think I'd prefer to flatten)

**Comment by Kangz** [comment]
Ah yeah flattening works as well, I'm not looking forward to the breaking change though.

**Comment by kainino0x** [comment]
I forgot it's not flattened in the JS API, so probably just renaming makes more sense to match (it's easier anyway)

**Comment by kainino0x** [comment]
Fixed tentatively, leaving `!discuss` to confirm.

**Comment by kainino0x** [comment]
Nov 25 meeting:

*   Renamed already to `WGPUComputeStage`. OK? (Note "Stage" vs "State" difference from `WGPUVertexState`/`WGPUFragmentState`)
*   CF: Think inconsistency is confusing. If adding more stages or whatever they would also be State.
*   **Rename to `WGPUComputeState`**
