### ISSUE TITLE
Default feature level in the C API as well

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#412]
> Prior to this it would have been allowed to call `wgpuInstanceRequestAdapter(instance, nullptr)` to get any adapter that the instance chooses. Can't we say that it defaults to core like the JS API?

_Originally posted by @Kangz in https://github.com/webgpu-native/webgpu-headers/pull/399#discussion_r1837732648_

**Comment by kainino0x** [comment]
Nov 21 meeting:

- KN: We previously discussed making Compatibility the default. Corentin prefers to default to Core to match JS. Kind of nice to make it required, but then the whole WGPURequestAdapterOptions struct becomes required. OTOH, non-breaking to add default later.
- CF: wgpu doesn't really have compatibility mode but effectively defaults to Core. Would prefer to make this required, but can see the argument for defaulting to core. Have at times regretted the default to core in wgpu, but WebGPU is already more limited.
- **Default to core.**
