### ISSUE TITLE
Abbreviate all-zero INIT macros as `{0}`?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#423]
Many of the INIT values (for `base`/`standalone` structs) will actually be all-zero, so equivalent to zero-initialization `{}`.
For those we could reduce the size of the header by just generating `{}` instead.

INIT structs are issue #158, PR #422

**Comment by eliemichel** [comment]
It seems that `{}` is not valid in C (it is reported by CI to be a non-standard GNU extension), we should rather use `{0}`.

**Comment by kainino0x** [comment]
Discussed on #427:

> - Should we have INIT macros when they are equivalent to zero-init, and therefore not really necessary? (see also "Abbreviate all-zero INIT macros as {0}? [#423](https://github.com/webgpu-native/webgpu-headers/issues/423)")
>   * **Keep for same reason**
>   * CF: Think we should not abbreviate. They're a form of documentation.
