### ISSUE TITLE
Behavior of NaNs and Infinities passed as float/double

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#466]
The JS API throws an exception (or rejects a promise with an exception) if NaN or Infinity is passed into any float/double (this rule comes from WebIDL; we don't use `unrestricted` which would lift it).

What should webgpu.h do when NaN or Infinity is passed to a required float/double, or Infinity is passed to an optional float/double (`depthClearValue`)?

The obvious answer is to produce a regular validation error, but Wasm implementations would _technically_ need to detect these and inject them into the error scope. In practice, this is really unnecessary and impractical, so Wasm implementations would probably just crash by hitting the aforementioned JS exception. We could maybe say "may crash, and if not produces a validation error" I guess?

Forked from isnan question on #427.

**Comment by eliemichel** [comment]
Could be deemed as "undefined behavior", which in practice throws in JS and does whatever in native? Or do we want to avoid UB as much as possible?

**Comment by kainino0x** [comment]
We have been mostly avoiding UB as much as possible, however in this case I think it's unreasonable to fully define the behavior. Even trying to specify it as a crash gets into too many details (what if you catch the Wasm trap and handle it somehow, what if you re-enter Wasm from a new entrypoint; in native, what if you have signal handlers, etc.)

**Comment by kainino0x** [comment]
Dec 12 meeting:

* What happens if you pass infinity/nan to a required float, or infinity to an optional float?  
* KN: Only problem is for wasm, otherwise validation error makes most sense.
* CF: Can we just say exactly that it will cause an exception in wasm? Not make it more undefined than necessary.
* **Do that.**

**Comment by kainino0x** [comment]
I should make a list of what this applies to exactly (`depthClearValue`, `WGPUColor`, ..?).

**Comment by kainino0x** [comment]
Here's the list of all floats and doubles:

- nullable floats
  - `depthClearValue`
- non-nullable floats
  - `lodMinClamp`, `lodMaxClamp`, `depthBiasSlopeScale`, `depthBiasClamp`, `setViewport()` args, 
- non-nullable doubles used as numeric "unions" (see also https://github.com/gpuweb/gpuweb/issues/5020):
  - `WGPUColor.*`, `WGPUConstantEntry.value`

> * Can we just say exactly that it will cause an exception in wasm?

To be more precise we should say it _may_ cause an exception in wasm. On the off chance that either the JS spec changes or some wasm implementation wants to avoid crashing on non-finite inputs.

**Comment by kainino0x** [comment]
Needs only docs.
