### ISSUE TITLE
WebGPU-Native -> WASI

### ISSUE THREAD

**Issue by tqchen** [webgpu-native/webgpu-headers#48]
As part of the discussion here https://github.com/WebAssembly/WASI/issues/276

There seems to be enough interest to bring webgpu native to WASI(on the wasi side). It would be welcoming devlopment that potentially makes webgpu-native run on wasm vms besides the web env. Just want to bring up the attention from this community, and see if it is of interest to the webgpu-native community (@lachlansneff already volunteered)

**Comment by doug-moen** [comment]
There is an open issue to add WebGPU to WASI here: https://github.com/WebAssembly/WASI/issues/53

**Comment by Kangz** [comment]
Can you highlight what would be the difference between `wasi-webgpu` and `webgpu.h` + the WebGPU specification? Would it basically add discussion of the event model and maybe more precisions about what happens on mapping?

**Comment by tqchen** [comment]
My hope is that there shouldn't be any difference ideally, to just land the webgpu-native as a formal wasi spec.

**Comment by Kangz** [comment]
`webgpu.h` is not just for WASI though but other native uses, so we'll have to see what the implications are.

**Comment by tqchen** [comment]
@Kangz I agree, that is why I actually hope you and @kvark could champion the wasi-webgpu spec if possible, to ensure the consistency between the specs.

**Comment by kainino0x** [comment]
IMO adding WebGPU as a WASI spec should be outside the domain of this group. We'll define the header and API contracts and bringing it to WASI should hopefully be mechanical.

If there are changes or decisions that need to be made about webgpu.h in order to support WASI, please file new issues!
For tracking, I'm closing this issue for now.
