### ISSUE TITLE
Change "FromHTMLCanvasId" to "FromHTMLSelector"?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#54]
On https://github.com/emscripten-core/emscripten/pull/11361#discussion_r436039353 @juj suggests that we select using `document.querySelector` instead of `document.getElementById` as it's more flexible and matches the behavior of the rest of Emscripten.

I originally considered doing this but stuck with `getElementById` to begin with for simplicity. However `querySelector` is probably the most "modern web" way to do this. It returns 0-1 results (only the first thing matching the selector) in a standard/reliable way.

WDYT?

**Comment by Kangz** [comment]
Sounds good, although it would be nice to have Canvas in the name. What about `FromCanvasHTMLSelector`?

**Comment by kainino0x** [comment]
Makes sense and matches the old name.
