### ISSUE TITLE
Synchronous validation in getMappedRange

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#64]
How should synchronous validation errors be exposed in getMappedRange? It can return null, but that doesn't tell the caller what went wrong. This would probably be fine, except e.g. Chromium needs to know what string to attach to the DOMException it generates. To do that now it needs to duplicate all of the validation that's already in getMappedRange.

**Comment by kainino0x** [comment]
(Which is especially problematic for the overlapping-range validation.)

**Comment by Kangz** [comment]
IMHO the overlapping range validation should be on the Blink side only, because it stems from limitations of `ArrayBuffer`. Same thing for the alignment restrictions.

**Comment by kainino0x** [comment]
Good point. Perhaps no issue here then.

**Comment by kainino0x** [comment]
from last week's meeting: At least the safe Rust API will keep this validation because it's required for Rust safety guarantees. wgpu-core and the C API don't necessarily have to, still.

**Comment by Kangz** [comment]
Do we have an explanation of why this is needed for the Rust safety guarantees? It seems it would only be to get mutable ranges?

**Comment by cwfitzgerald** [comment]
Correct, const overlaps are fine, mutable overlaps are not.

**Comment by kainino0x** [comment]
In June we had concluded:
> make this Result-like, error is either an enum or a string (who owns the string?)

However we discussed this more today in the broader context of reporting synchronous errors and came to a simpler conclusion:

*   CF: Can’t do an enum because in WASM we can’t convert the JS Error to an enum.
*   Could return a struct that you have to FreeMembers. Very annoying because you have to do this for every single GetMappedRange call.
*   Out param for the error, and if you pass it then you have to FreeMembers?
*   CF: Worried about inconsistencies across the API
*   KN: Just return a two-state enum so we don’t have to convert JS error to enum? (Actually that’s the same as returning nullptr)
    *   CF: Implementation-defined logging
*   KN: There’s two error cases: overlapping (mutable) ranges, and asking for a mutable pointer to immutable mapping.
*   **Return nullptr on error, with implementation-defined logging**
