### ISSUE TITLE
LoadOp and StoreOp have different order

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#65]
LoadOp and StoreOp have different orders: {clear, load} vs {store, clear}.
This isn't inherently a problem but if you accidentally use storeOp=WGPULoadOp_Clear or loadOp=WGPUStoreOp_Clear then the result could be confusing.

Arguably WGPUStoreOp_Store should be 0 because it's the default value in JS, but semantically that's part of GPURenderPassColorAttachmentDescriptor, not GPUStoreOp. Depending on how closely we want to match upstream, we could:
- Ignore that fact and flip WGPULoadOp
- Change the enums to be 1 and 2, with 0 being invalid
- ^, and add WGPUStoreOp_Undefined = 0 which applies the default in WGPURenderPassColorAttachmentDescriptor

```
typedef enum WGPULoadOp {
    WGPULoadOp_Clear = 0x00000000,
    WGPULoadOp_Load = 0x00000001,
    WGPULoadOp_Force32 = 0x7FFFFFFF
} WGPULoadOp;

typedef enum WGPUStoreOp {
    WGPUStoreOp_Store = 0x00000000,
    WGPUStoreOp_Clear = 0x00000001,
    WGPUStoreOp_Force32 = 0x7FFFFFFF
} WGPUStoreOp;
```

**Comment by kvark** [comment]
> This isn't inherently a problem but if you accidentally use storeOp=WGPULoadOp_Clear or loadOp=WGPUStoreOp_Clear then the result could be confusing.

how would changing the order prevent this from happening?

**Comment by kainino0x** [comment]
It wouldn't create a compile error, but it would make using the wrong Clear be the same as the other Clear.

**Comment by Kangz** [comment]
I'd +1 adding an Undefined, that's somewhat similar to https://github.com/webgpu-native/webgpu-headers/issues/45 actually but I haven't had a chance to go back to that yet.

**Comment by kainino0x** [comment]
(This isn't really a problem anymore since StoreOp "Clear" got renamed to "Discard" but let's still make it consistent.)
