### ISSUE TITLE
Readonly vs ReadOnly

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#72]
If we take a direct casing conversion from JS/IDL's `"readonly-storage"` to camel case `ReadonlyStorage` then it looks maybe a little funny. Should we case it as `ReadOnlyStorage`?

Note this also comes up again soon in WGPUStorageTextureAccess.

Should we keep consistency with IDL (`Readonly`), break with it (`ReadOnly`), or change the IDL (`"read-only-storage"`)?

cc @toji

**Comment by kainino0x** [comment]
Notably the IDL also has fields with names like "depthReadOnly" so maybe we should change the IDL.

**Comment by doug-moen** [comment]
According to multiple dictionaries of the English language, the correct spelling is "read-only" with a hyphen. If there are already inconsistencies that need to be resolved, then I would standardize on ReadOnly rather than Readonly.

**Comment by kvark** [comment]
let's raise this up with WebGPU API spec then, first
