### ISSUE TITLE
How to pass features in the device descriptor? 

### ISSUE THREAD

**Issue by austinEng** [webgpu-native/webgpu-headers#74]
In the JS API,  the device descriptor takes a sequence of strings which are the feature names. The list of features (as strings) can also be queried on the adapter.

In the C API I see two options to represent this. (actually three, but the last one seems bad)
 1. List of null-terminated strings. This is how Vulkan does device extensions. We'd have a list of feature names somewhere and ask people not to make extensions with conflicting names.
 2. List of enums - we'd ask people making extensions to make a PR to webgpu-headers to reserve their enum values. This is what SPIR-V does for OpCodes introduced by an extension. Emscripten or whatever translates C -> JS would need to have a table mapping the enums to strings for the JS API.
 3. A struct where each feature is a boolean member. This is not easily extensible.
 
@kvark @Kangz what do you think?

I have a slight preference for (1) since it's the most direct translation to JS, so it would be less maintenance in the C->JS layer. And, I don't think it's that important to optimize passing the list of features since it only happens on device creation.

Edit: Nevermind, I remembered we have string enums in JS anyway so there need to be enum tables maintained anyway. I prefer (2) then.

**Comment by Kangz** [comment]
I don't have a strong preference between 1) and 2). I agree that webgpu.h will need to become some form of registry in particular for `sType` values so that extensions don't collide.

**Comment by kvark** [comment]
One outcome for (2) would be that, if wgpu-native or Dawn want to support an extension, they essentially need a consensus with this subgroup that this extension is OK. I think it would be a concern if our subgroup was big, but given that it's only a few of us, this seems to be totally feasible.

**Comment by doug-moen** [comment]
The use case I'm thinking of is when an independent group forks wgpu-native or Dawn, develops an extension (possibly for a year or two) then presents the extension to this group for inclusion in webgpu native, once the benefits have been proven in application code.

The benefit of the list-of-strings representation in this context is not needing to modify webgpu.h for this purpose while developing the extension. Also, the extension namespace is much larger with strings, so it's easier to use a naming convention that avoids conflict with other work-in-progress extensions.

**Comment by kainino0x** [comment]
I like (1) for that reason as well.

**Comment by kvark** [comment]
They can also just `transmute` a unique `u32` value into the enum that represents extensions, and work this way without modifying the main header. I think in C it's not UB if enums contain unknown values. Perhaps, in C++ it's different? Are you even going to use the same `enum` in C++, or define a new one?

**Comment by doug-moen** [comment]
@kvark said "I think in C it's not UB if enums contain unknown values. Perhaps, in C++ it's different?"

It is undefined behaviour in C++. Reference: https://wiki.sei.cmu.edu/confluence/display/cplusplus/INT50-CPP.+Do+not+cast+to+an+out-of-range+enumeration+value

**Comment by austinEng** [comment]
It's only UB if you're not using the fixed underlying type. Specifying it as a particular type makes it ok.
In C++ we would do

```c++
enum class FeatureName : uint32_t {
  TextureCompressionBC = 0;
  // ....
  VendorSpecificSomething = 38024;
};
```

We could ask individuals or groups to reserve a large block of say 100 enums if they plan on doing a lot of internal work. They don't have to be named, just reserved.

**Comment by kainino0x** [comment]
I was thinking of suggesting these things. But sure, we could do all this, but what's the benefit over strings?

**Comment by doug-moen** [comment]
Khronos has a lot of experience in this area. I suggest adopting the relevant methods and procedures in Vulkan for defining extensions, rather than designing something new.
https://www.khronos.org/registry/vulkan/specs/1.2/styleguide.html#extensions

**Comment by austinEng** [comment]
For what it's worth, it's not something new. Both Vulkan and SPIR-V have vendors reserve enums. They do some parts with strings and some parts with enums. I'd be curious to understand more of the reason why the extension names are strings. I find that enums are less error prone for both the developer and the implementation - you can't misspell it.

That being said, I do see that it's helpful to have a particular naming convention so that assuming everyone follows it, it's easy to make sure the extension you're developing doesn't conflict with something else. It doesn't solve the problem perfectly because any enums the extension introduces can still conflict. We will always need some registry to reserve enums.

I don't feel very strongly either way, so if there are more good reasons to use strings then we can do that.

**Comment by kvark** [comment]
I've had mis-typed the extension name a few times when programming Vulkan, and that was only discovered at run-time, possibly on another users machine. With all other aspects being equal, I find the enums to at least guard against this issue.

**Comment by doug-moen** [comment]
Vulkan deals with the problem of mistyping extension strings by providing macros like this in the Vulkan header files:

#define VK_NV_FILL_RECTANGLE_EXTENSION_NAME "VK_NV_fill_rectangle"

**Comment by doug-moen** [comment]
To deal with the "undefined behaviour" problem of extending an enum with out-of-range enum values, Vulkan uses the following coding pattern:
```
typedef enum VkResult = {
    ....
    VK_RESULT_MAX_ENUM = 0x7FFFFFFF
} VkResult;
```
The C++ compiler is forced to use a numeric type wide enough to represent 0x7FFFFFFF.

**Comment by kvark** [comment]
If people use defines, then we might as well have them in enum values and skip the strings altogether :)

**Comment by Kangz** [comment]
Ok it seems everyone is in agreement that enums are the way to go?

**Comment by doug-moen** [comment]
My concern is that using strings on the JS side and integers on the C side creates unnecessary complexity. The WebIDL description of WebGPU will use strings, and any language binding based on the WebIDL will use strings. When WASI adopts WebGPU as its GPU API, then WASI will use strings, since that's what the WebIDL says.

I'm developing a WebGPU app in C++. One use case I need to test is compiling my C++ code to WebAssembly and running it outside a web browser using WASI. As @austinEng says, Emscripten will need a table mapping integers to strings, because the WASM code uses strings. Assuming the WASI runtime uses webgpu.h, then it will need a table mapping strings to integers.

Now let's say I am developing a private WebGPU extension. I need to allocate both an integer and a string for my extension. I need to provide a table mapping integers to strings to Emscripten, and I need to provide a table mapping strings to integers to WASI. Why is this so complicated? Why not just use strings everywhere?

**Comment by Kangz** [comment]
We already have that complexity for regular enums (like `GPUTextureFormat`) which are strings in the WebIDL and real enums in webgpu.h. Does WASI plan to implement regular enums using strings?

 I don't think it's a lot of complexity for Emscripten because we're already able to generate all the enum tables from Dawn's `dawn.json` file.

> Now let's say I am developing a private WebGPU extension. I need to allocate both an integer and a string for my extension. I need to provide a table mapping integers to strings to Emscripten, and I need to provide a table mapping strings to integers to WASI. Why is this so complicated? Why not just use strings everywhere?

Strings are slow compared to enums in C so in general you want to use C enums when possible (though maybe not for extensions because it is not hot code). When adding an extension you will most likely need new enum values, new entrypoints, new structs or new extension structs. In all these case you need to modify emscripten anyway so the additional enum->string conversion isn't really an issue.

**Comment by doug-moen** [comment]
Maybe there is a misunderstanding. In WebIDL, string types and enum types are different concepts. In the WebIDL description of WebGPU, will an extension name be represented by type `DomString`, or will there be an enum type definition, `enum ExtensionName`? If we use a string type in the WebIDL and an enum type in the C header file, it's inconsistent and the difference will add complexity. If it's an enum type in both places, that's different.

**Comment by Kangz** [comment]
There's a [`GPUFreatureName`](https://gpuweb.github.io/gpuweb/#enumdef-gpufeaturename) enum already so I think this solve your concern :D
