### ISSUE TITLE
Meaning of TextureViewDescriptor mipLevelCount==0

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#77]
In JS, `mipLevelCount` of `0` really means `0`. If you want "auto" (baseMipLevel..end) then you have to specify undefined.

In C, should `0` mean "auto" or should it mean `0` (and `WGPU_WHOLE_SIZE` means "auto")?

EDIT: Also applies to `arrayLayerCount`.

**Comment by kainino0x** [comment]
see also gpuweb/gpuweb#945

**Comment by kvark** [comment]
Vulkan requires the array layer count to be >= 1 (see https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageViewCreateInfo.html)
So I suggest we just make `arrayLayerCount == 0` to be an error in WebGPU (and same goes to `mipLevelCount`).

**Comment by kainino0x** [comment]
If they're not errors already they definitely should be. Then it makes sense to keep 0 meaning "auto" in webgpu.h. (Blink will have to inject a validation error if it sees 0, because passing it through would have the wrong behavior and fail tests.)

**Comment by Richard-Yunchao** [comment]
Agreed! 

mipLevelCount and size.depth (size.depthOrArrayLayers now?) are required to be non-zero (>=1) in TextureDescriptor in WebGPU. I think it's good for mipLevelCount/arrayLayerCount in TextureViewDescriptor to be consistent. 

If we want to use the default behavior, just leave mipLevelCount/arrayLayerCount to be undefined. We don't need two methods for the same purpose. IMHO, leaving them "undefined" is more suitable than explicitly assigning zeros for the default behavior.

**Comment by almarklein** [comment]
I'd be in favor of 0 meaning the default too; it'd make the code in wgpu-py simpler. It looks like in #109 a different approach was applied though. Was this an oversight, or has the agreement changed since the last comment here?

https://github.com/webgpu-native/webgpu-headers/blob/4b4dbc3253ba03a1a7b7c42e18cead9dfc1142b8/webgpu.h#L59-L60

**Comment by kainino0x** [comment]
Yes, we've changed our approach since the last comment here.

**Comment by kainino0x** [comment]
meeting:
Agreed that C `0` should mean the same thing as JS `0` (it's a validation error)
and C `UINT32_MAX` should mean the same thing as JS `undefined` (use all of the miplevels).
The reason for this is that otherwise it's annoying to implement the JS API correctly over the C API (you have to inject an error and conjure up an invalid GPUTexture object to return)

**Comment by kainino0x** [comment]
And since we already have WGPU_MIP_LEVEL_COUNT_UNDEFINED and WGPU_ARRAY_LAYER_COUNT_UNDEFINED in the C header this can be closed. (It doesn't super specifically need documentation because it follows the convention used elsewhere, where numbers always pass through directly except for these predefined ones.)
