### ISSUE TITLE
Make the blend state nullable

### ISSUE THREAD

**Issue by kvark** [webgpu-native/webgpu-headers#79]
Need to update the headers according to https://github.com/gpuweb/gpuweb/pull/1134

**Comment by Kangz** [comment]
@toji will likely is looking at updated Dawn to the new `GPURenderPipelineDescriptor` and nullable blend states should be part of the overall PR to make webgpu.h match that.

**Comment by toji** [comment]
This has landed in Dawn, but is currently listed under `GPURenderPipelineDescriptor2` while we go through a deprecation period for the old descriptor format.

**Comment by Kangz** [comment]
webgpu.h in this repo has already been updated to that new descriptor, closing as fixed!
