### ISSUE TITLE
Issues with C / C++ bool type.

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#84]
This is an issue that someone (graphite?) raised on Discord but didn't file here. The `bool` types in C/C++ are kinda weird and can not match, especially when put back to back. `webgpu.h` shouldn't rely on this type, and instead do something like Vulkan's `VkBool32`.

**Comment by Beyley** [comment]
is there an ETA for a fix landing in this repository? movement seems to be happening chromium side, but i dont see an open PR over here, should i open a PR for adding a typedef for WGPUBool?

**Comment by lokokung** [comment]
Yea this should be coming within the next week. I am trying to land the effective changes on Chromium side to make sure it will work there. I can create the corresponding PR here once that's progressed a bit more.
