### ISSUE TITLE
WGPUShaderModuleWGSLDescriptor needs a byteLength field

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#90]
WGSL code can contain nulls (EDIT: only in comments), so the string cannot be treated as null-terminated. Instead a byteLength field would be needed.

https://github.com/gpuweb/gpuweb/issues/1816

**Comment by Kangz** [comment]
+1 and the same for entrypoint names and specialization constant names (because if they allow UTF8 then some code points will have representations containing null bytes). I suggest we let byteLength of 0 mean "use strlen" for simplicity.

**Comment by doug-moen** [comment]
Why is it important to support null characters in entrypoint names? Underlying platforms like Vulkan do not support this, so WebGPU should not support it either.

<https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineShaderStageCreateInfo.html>
> pName is a pointer to a null-terminated UTF-8 string specifying the entry point name of the shader for this stage.

**Comment by Kangz** [comment]
It seems I incorrectly understood things in the meeting and UTF8 encoding doesn't have zero bytes except to represent ASCII null. So it's not possible to have an identifier name (like entry point or pipeline overridable constant) that contains a null byte. This is only possible for WGSL code because technically the null byte is allowed in comments.

**Comment by kvark** [comment]
I like the "byteLength of 0 mean use strlen for simplicity" idea.

**Comment by kainino0x** [comment]
I'm not totally sure about 0. It could result in surprise undefined behavior, for example for a C++ string class which may not have a terminating null (e.g. `std::string` prior to C++11).

```c++
MyString src{}; // initialize to empty string
wgslDescriptor.source = src.data(); // .c_str() would have been OK
wgslDescriptor.sourceByteLength = src.size();
```

**Comment by Kangz** [comment]
Maybe another `0xFFFFFFFF` constant then?

**Comment by doug-moen** [comment]
> Maybe another 0xFFFFFFFF constant then?

Why is it necessary to innovate? I'm not familiar with other C APIs that work this way. Why not just use the simplest possible design, which is that `sourceByteLength` is the size of the array, exactly as the name says? This is aligned with all of the APIs in the C standard library and POSIX standard that specify an array of characters using a `char*` and a `size_t`. If the API is simple and follows a well known standard and convention then it won't cause surprises.

**Comment by dneto0** [comment]
I wasn't aware of this discussion, but did drive the WGSL side: #2294  
We decided that NUL characters would *not* be permitted in WGSL source code. The only place they might have been would have been in comments.

**Comment by Kangz** [comment]
Great! I love when issues solve themselves by just waiting ^^

Since the strings cannot contain `\0` we can keep them null-terminated.
