### ISSUE TITLE
Waiting for asynchronous operations to finish (polling)

### ISSUE THREAD

**Issue by athas** [webgpu-native/webgpu-headers#91]
[wgpu's compute example uses wgpuDevicePoll](https://github.com/gfx-rs/wgpu-native/blob/master/examples/compute/main.c#L126) to block until the memory is mapped.  This works, but `wgpuDevicePoll` is wgpu-specific.  The JS API returns a promise that can be used for blocking here, but I cannot see how something similar can be done using just webgpu.h.  Some mechanism for blocking until asynchronous operations are done should probably be added.

**Comment by Kangz** [comment]
This is a common pain point. Likewise in Dawn, people use wgpuDeviceTick to the same effect. However it is a constraint of the web platform at this moment that the browser can only fire promises (so the result of mapAsync) when control is yielded back to it. Fixing this would require more than a webgpu.h change, it would need so core JS event loop change to allow pumping the loop from inside JS/WASM execution.

There no effort started around this yet and it's not clear if it would be something W3C would be interested in. CC @kainino0x

**Comment by athas** [comment]
What is a non-blocking tick?

I think exposing a synchronise-the-world operation is a fine stopgap solution.  It's not efficient, but it is simple to understand, and does not block more elaborate mechanisms from being added in the future (and one could even argue that such crude synchronisation is useful for debugging).

**Comment by austinEng** [comment]
I think a non-blocking "tick" is what `wgpuDevicePoll` is if you set the `force_wait` argument to false? This is what Dawn's wgpuDeviceTick does.

I thought we had previously discussed but moving it to the instance as wgpuInstanceProcessEvents. It would be responsible for checking any callbacks and calling them if they have finished, in a non-blocking manner.

**Comment by athas** [comment]
Ah, so wgpuDeviceTick will let WebGPU do *something*, although not necessarily *everything*, and then I can call it in a loop until the callback for the event I am interested in has been run?

**Comment by Kangz** [comment]
In native this works with Dawn, but it won't work when running in WebAssembly because you need to yield back control to the browser.

**Comment by athas** [comment]
Sure, it'd just be a stopgap solution for now.  It would still be nice with a solution that works for both wgpu and Dawn, but I suppose I can `#ifdef` my way out of it.

**Comment by eliemichel** [comment]
A workaround that works for both Dawn and wgpu-native is to submit an empty command buffer:

```
bool done = false;
// [...] Call wgpuBufferMapAsync with a callback that turns done to true

while (!done) {
    // Do nothing, this checks for ongoing asynchronous operations and call their callbacks if needed
    wgpuQueueSubmit(queue, 0, nullptr);
}
```

**Comment by unvestigate** [comment]
To spare you the same confusion I was going through I'd like to mention that right now, for Dawn, you have to call the wgpuDeviceTick() function to have your callbacks fire.

**Comment by kainino0x** [comment]
Forgot we had this issue filed, for some reason! I'm planning to solve this in #199.
