### ISSUE TITLE
Compatibility with iOS simulator

### ISSUE THREAD

**Issue by kvark** [webgpu-native/webgpu-headers#92]
@CurryPseudo found out that iOS simulator doesn't support comparison sampler states, see https://github.com/gfx-rs/wgpu/issues/1715#issuecomment-887179553
This means we can't run WebGPU proper on it, and it's quite sad for development.

Possible solutions:
  - draft a native-only feature for immutable samplers
  - add "downlevel" features to make it more compatible with GL, DX11, and things like iOS simulator. It would have a flag for comparison samplers, basically.
  - push Apple to make the iOS simulator more capable
  - live with the problem forever

**Comment by Kangz** [comment]
IMHO the iOS simulator shouldn't be a requirement for a "downlevel" that's standardized at W3C because it has extra limitations compared to what real hardware can do. FYI old iOS versions also don't have BaseVertex and BaseInstance.

We could have a native-only extension for device creation that opts into the validation limitation of specific hardware / OS combinations for easy testing though.

**Comment by kainino0x** [comment]
Am I understanding correctly that comparison samplers also aren't supported on real A8 hardware (not just the simulator which is supposed to match A8)? If so, it definitely impacts the main group as we are supposed to run on A8 ([MTLGPUFamilyApple2](https://developer.apple.com/documentation/metal/mtlgpufamily/mtlgpufamilyapple2?language=objc)): https://github.com/gpuweb/gpuweb/issues/1069

**Comment by kvark** [comment]
See https://github.com/gpuweb/gpuweb/pull/356 .
IIRC, the group just said it will not ship on devices that don't support this (unfortunately).

**Comment by kainino0x** [comment]
Ah, I forgot about this. I am pretty sure there's at least one restriction we still have solely for A8, so if that's the case we should try to find it and lift it.

**Comment by kainino0x** [comment]
I suspect this issue is obsolete by now
